// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hls_hough_HH_
#define _hls_hough_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "hls_hough_line.h"
#include "AXIvideo2Mat.h"
#include "fifo_w8_d64_A.h"

namespace ap_rtl {

struct hls_hough : public sc_module {
    // Port declarations 50
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > src_axi_V_data_V_dout;
    sc_in< sc_logic > src_axi_V_data_V_empty_n;
    sc_out< sc_logic > src_axi_V_data_V_read;
    sc_in< sc_lv<4> > src_axi_V_keep_V_dout;
    sc_in< sc_logic > src_axi_V_keep_V_empty_n;
    sc_out< sc_logic > src_axi_V_keep_V_read;
    sc_in< sc_lv<4> > src_axi_V_strb_V_dout;
    sc_in< sc_logic > src_axi_V_strb_V_empty_n;
    sc_out< sc_logic > src_axi_V_strb_V_read;
    sc_in< sc_lv<1> > src_axi_V_user_V_dout;
    sc_in< sc_logic > src_axi_V_user_V_empty_n;
    sc_out< sc_logic > src_axi_V_user_V_read;
    sc_in< sc_lv<1> > src_axi_V_last_V_dout;
    sc_in< sc_logic > src_axi_V_last_V_empty_n;
    sc_out< sc_logic > src_axi_V_last_V_read;
    sc_in< sc_lv<1> > src_axi_V_id_V_dout;
    sc_in< sc_logic > src_axi_V_id_V_empty_n;
    sc_out< sc_logic > src_axi_V_id_V_read;
    sc_in< sc_lv<1> > src_axi_V_dest_V_dout;
    sc_in< sc_logic > src_axi_V_dest_V_empty_n;
    sc_out< sc_logic > src_axi_V_dest_V_read;
    sc_out< sc_lv<32> > dst_axi_V_data_V_din;
    sc_in< sc_logic > dst_axi_V_data_V_full_n;
    sc_out< sc_logic > dst_axi_V_data_V_write;
    sc_out< sc_lv<4> > dst_axi_V_keep_V_din;
    sc_in< sc_logic > dst_axi_V_keep_V_full_n;
    sc_out< sc_logic > dst_axi_V_keep_V_write;
    sc_out< sc_lv<4> > dst_axi_V_strb_V_din;
    sc_in< sc_logic > dst_axi_V_strb_V_full_n;
    sc_out< sc_logic > dst_axi_V_strb_V_write;
    sc_out< sc_lv<1> > dst_axi_V_user_V_din;
    sc_in< sc_logic > dst_axi_V_user_V_full_n;
    sc_out< sc_logic > dst_axi_V_user_V_write;
    sc_out< sc_lv<1> > dst_axi_V_last_V_din;
    sc_in< sc_logic > dst_axi_V_last_V_full_n;
    sc_out< sc_logic > dst_axi_V_last_V_write;
    sc_out< sc_lv<1> > dst_axi_V_id_V_din;
    sc_in< sc_logic > dst_axi_V_id_V_full_n;
    sc_out< sc_logic > dst_axi_V_id_V_write;
    sc_out< sc_lv<1> > dst_axi_V_dest_V_din;
    sc_in< sc_logic > dst_axi_V_dest_V_full_n;
    sc_out< sc_logic > dst_axi_V_dest_V_write;
    sc_in< sc_lv<32> > rows;
    sc_in< sc_lv<32> > cols;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    hls_hough(sc_module_name name);
    SC_HAS_PROCESS(hls_hough);

    ~hls_hough();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    hls_hough_line* grp_hls_hough_line_fu_218;
    AXIvideo2Mat* grp_AXIvideo2Mat_fu_250;
    fifo_w8_d64_A* img_src_data_stream_s_fifo_U;
    fifo_w8_d64_A* img_dst_data_stream_s_fifo_U;
    sc_signal< sc_lv<7> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > dst_axi_V_data_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > exitcond_i_reg_384;
    sc_signal< sc_logic > dst_axi_V_keep_V_blk_n;
    sc_signal< sc_logic > dst_axi_V_strb_V_blk_n;
    sc_signal< sc_logic > dst_axi_V_user_V_blk_n;
    sc_signal< sc_logic > dst_axi_V_last_V_blk_n;
    sc_signal< sc_logic > dst_axi_V_id_V_blk_n;
    sc_signal< sc_logic > dst_axi_V_dest_V_blk_n;
    sc_signal< sc_lv<32> > t_V_2_reg_207;
    sc_signal< sc_lv<33> > ret_V_fu_281_p2;
    sc_signal< sc_lv<33> > ret_V_reg_370;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > grp_hls_hough_line_fu_218_ap_ready;
    sc_signal< sc_logic > grp_hls_hough_line_fu_218_ap_done;
    sc_signal< sc_lv<1> > exitcond1_i_fu_287_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > i_V_fu_292_p2;
    sc_signal< sc_lv<32> > i_V_reg_379;
    sc_signal< sc_lv<1> > exitcond_i_fu_298_p2;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter0;
    sc_signal< sc_lv<8> > img_dst_data_stream_s_dout;
    sc_signal< sc_logic > img_dst_data_stream_s_empty_n;
    sc_signal< sc_logic > img_dst_data_stream_s_read;
    sc_signal< sc_logic > dst_axi_V_id_V1_status;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<32> > j_V_fu_303_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > axi_last_V_fu_313_p2;
    sc_signal< sc_lv<1> > axi_last_V_reg_393;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state6;
    sc_signal< sc_logic > grp_hls_hough_line_fu_218_ap_start;
    sc_signal< sc_logic > grp_hls_hough_line_fu_218_ap_idle;
    sc_signal< sc_logic > grp_hls_hough_line_fu_218_src_data_stream_V_read;
    sc_signal< sc_lv<8> > grp_hls_hough_line_fu_218_dst_data_stream_V_din;
    sc_signal< sc_logic > grp_hls_hough_line_fu_218_dst_data_stream_V_write;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_ap_start;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_ap_done;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_ap_idle;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_ap_ready;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_AXI_video_strm_V_data_V_read;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_AXI_video_strm_V_keep_V_read;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_AXI_video_strm_V_strb_V_read;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_AXI_video_strm_V_user_V_read;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_AXI_video_strm_V_last_V_read;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_AXI_video_strm_V_id_V_read;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_AXI_video_strm_V_dest_V_read;
    sc_signal< sc_lv<8> > grp_AXIvideo2Mat_fu_250_img_data_stream_V_din;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_img_data_stream_V_write;
    sc_signal< sc_lv<32> > t_V_reg_196;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > grp_hls_hough_line_fu_218_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<8> > img_src_data_stream_s_dout;
    sc_signal< sc_logic > img_src_data_stream_s_empty_n;
    sc_signal< sc_logic > img_src_data_stream_s_read;
    sc_signal< sc_logic > img_dst_data_stream_s_full_n;
    sc_signal< sc_logic > img_dst_data_stream_s_write;
    sc_signal< sc_logic > grp_AXIvideo2Mat_fu_250_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > img_src_data_stream_s_full_n;
    sc_signal< sc_logic > img_src_data_stream_s_write;
    sc_signal< sc_logic > dst_axi_V_id_V1_update;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<1> > tmp_user_V_fu_138;
    sc_signal< sc_lv<33> > lhs_V_cast_fu_278_p1;
    sc_signal< sc_lv<33> > tmp_i_cast_fu_309_p1;
    sc_signal< sc_lv<7> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<7> ap_ST_fsm_state1;
    static const sc_lv<7> ap_ST_fsm_state2;
    static const sc_lv<7> ap_ST_fsm_state3;
    static const sc_lv<7> ap_ST_fsm_state4;
    static const sc_lv<7> ap_ST_fsm_state5;
    static const sc_lv<7> ap_ST_fsm_pp0_stage0;
    static const sc_lv<7> ap_ST_fsm_state8;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<33> ap_const_lv33_1FFFFFFFF;
    static const sc_lv<24> ap_const_lv24_FFFFFF;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state8();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state6_pp0_stage0_iter0();
    void thread_ap_block_state7_pp0_stage0_iter1();
    void thread_ap_condition_pp0_exit_iter0_state6();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_axi_last_V_fu_313_p2();
    void thread_dst_axi_V_data_V_blk_n();
    void thread_dst_axi_V_data_V_din();
    void thread_dst_axi_V_data_V_write();
    void thread_dst_axi_V_dest_V_blk_n();
    void thread_dst_axi_V_dest_V_din();
    void thread_dst_axi_V_dest_V_write();
    void thread_dst_axi_V_id_V1_status();
    void thread_dst_axi_V_id_V1_update();
    void thread_dst_axi_V_id_V_blk_n();
    void thread_dst_axi_V_id_V_din();
    void thread_dst_axi_V_id_V_write();
    void thread_dst_axi_V_keep_V_blk_n();
    void thread_dst_axi_V_keep_V_din();
    void thread_dst_axi_V_keep_V_write();
    void thread_dst_axi_V_last_V_blk_n();
    void thread_dst_axi_V_last_V_din();
    void thread_dst_axi_V_last_V_write();
    void thread_dst_axi_V_strb_V_blk_n();
    void thread_dst_axi_V_strb_V_din();
    void thread_dst_axi_V_strb_V_write();
    void thread_dst_axi_V_user_V_blk_n();
    void thread_dst_axi_V_user_V_din();
    void thread_dst_axi_V_user_V_write();
    void thread_exitcond1_i_fu_287_p2();
    void thread_exitcond_i_fu_298_p2();
    void thread_grp_AXIvideo2Mat_fu_250_ap_start();
    void thread_grp_hls_hough_line_fu_218_ap_start();
    void thread_i_V_fu_292_p2();
    void thread_img_dst_data_stream_s_read();
    void thread_img_dst_data_stream_s_write();
    void thread_img_src_data_stream_s_read();
    void thread_img_src_data_stream_s_write();
    void thread_j_V_fu_303_p2();
    void thread_lhs_V_cast_fu_278_p1();
    void thread_ret_V_fu_281_p2();
    void thread_src_axi_V_data_V_read();
    void thread_src_axi_V_dest_V_read();
    void thread_src_axi_V_id_V_read();
    void thread_src_axi_V_keep_V_read();
    void thread_src_axi_V_last_V_read();
    void thread_src_axi_V_strb_V_read();
    void thread_src_axi_V_user_V_read();
    void thread_tmp_i_cast_fu_309_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
