// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_sobel,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku115-flvd1517-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.786125,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=27,HLS_SYN_DSP=0,HLS_SYN_FF=2406,HLS_SYN_LUT=9446,HLS_VERSION=2018_3}" *)

module hls_sobel (
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST,
        rows,
        cols,
        ap_clk,
        ap_rst_n,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        ap_start,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [31:0] INPUT_STREAM_TDATA;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [0:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [0:0] INPUT_STREAM_TID;
input  [0:0] INPUT_STREAM_TDEST;
output  [31:0] OUTPUT_STREAM_TDATA;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [0:0] OUTPUT_STREAM_TUSER;
output  [0:0] OUTPUT_STREAM_TLAST;
output  [0:0] OUTPUT_STREAM_TID;
output  [0:0] OUTPUT_STREAM_TDEST;
input  [31:0] rows;
input  [31:0] cols;
input   ap_clk;
input   ap_rst_n;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
input   ap_start;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_start_out;
wire    AXIvideo2Mat_U0_start_write;
wire    AXIvideo2Mat_U0_INPUT_STREAM_TREADY;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire    Sobel_U0_ap_start;
wire    Sobel_U0_ap_done;
wire    Sobel_U0_ap_continue;
wire    Sobel_U0_ap_idle;
wire    Sobel_U0_ap_ready;
wire    Sobel_U0_start_out;
wire    Sobel_U0_start_write;
wire    Sobel_U0_p_src_data_stream_0_V_read;
wire    Sobel_U0_p_src_data_stream_1_V_read;
wire    Sobel_U0_p_src_data_stream_2_V_read;
wire   [7:0] Sobel_U0_p_dst_data_stream_0_V_din;
wire    Sobel_U0_p_dst_data_stream_0_V_write;
wire   [7:0] Sobel_U0_p_dst_data_stream_1_V_din;
wire    Sobel_U0_p_dst_data_stream_1_V_write;
wire   [7:0] Sobel_U0_p_dst_data_stream_2_V_din;
wire    Sobel_U0_p_dst_data_stream_2_V_write;
wire    SubS_U0_ap_start;
wire    SubS_U0_ap_done;
wire    SubS_U0_ap_continue;
wire    SubS_U0_ap_idle;
wire    SubS_U0_ap_ready;
wire    SubS_U0_start_out;
wire    SubS_U0_start_write;
wire    SubS_U0_src_data_stream_0_V_read;
wire    SubS_U0_src_data_stream_1_V_read;
wire    SubS_U0_src_data_stream_2_V_read;
wire   [7:0] SubS_U0_dst_data_stream_0_V_din;
wire    SubS_U0_dst_data_stream_0_V_write;
wire   [7:0] SubS_U0_dst_data_stream_1_V_din;
wire    SubS_U0_dst_data_stream_1_V_write;
wire   [7:0] SubS_U0_dst_data_stream_2_V_din;
wire    SubS_U0_dst_data_stream_2_V_write;
wire    Scale_U0_ap_start;
wire    Scale_U0_ap_done;
wire    Scale_U0_ap_continue;
wire    Scale_U0_ap_idle;
wire    Scale_U0_ap_ready;
wire    Scale_U0_start_out;
wire    Scale_U0_start_write;
wire    Scale_U0_src_data_stream_0_V_read;
wire    Scale_U0_src_data_stream_1_V_read;
wire    Scale_U0_src_data_stream_2_V_read;
wire   [7:0] Scale_U0_dst_data_stream_0_V_din;
wire    Scale_U0_dst_data_stream_0_V_write;
wire   [7:0] Scale_U0_dst_data_stream_1_V_din;
wire    Scale_U0_dst_data_stream_1_V_write;
wire   [7:0] Scale_U0_dst_data_stream_2_V_din;
wire    Scale_U0_dst_data_stream_2_V_write;
wire    Erode_U0_ap_start;
wire    Erode_U0_ap_done;
wire    Erode_U0_ap_continue;
wire    Erode_U0_ap_idle;
wire    Erode_U0_ap_ready;
wire    Erode_U0_start_out;
wire    Erode_U0_start_write;
wire    Erode_U0_p_src_data_stream_0_V_read;
wire    Erode_U0_p_src_data_stream_1_V_read;
wire    Erode_U0_p_src_data_stream_2_V_read;
wire   [7:0] Erode_U0_p_dst_data_stream_0_V_din;
wire    Erode_U0_p_dst_data_stream_0_V_write;
wire   [7:0] Erode_U0_p_dst_data_stream_1_V_din;
wire    Erode_U0_p_dst_data_stream_1_V_write;
wire   [7:0] Erode_U0_p_dst_data_stream_2_V_din;
wire    Erode_U0_p_dst_data_stream_2_V_write;
wire    Dilate_U0_ap_start;
wire    Dilate_U0_ap_done;
wire    Dilate_U0_ap_continue;
wire    Dilate_U0_ap_idle;
wire    Dilate_U0_ap_ready;
wire    Dilate_U0_start_out;
wire    Dilate_U0_start_write;
wire    Dilate_U0_p_src_data_stream_0_V_read;
wire    Dilate_U0_p_src_data_stream_1_V_read;
wire    Dilate_U0_p_src_data_stream_2_V_read;
wire   [7:0] Dilate_U0_p_dst_data_stream_0_V_din;
wire    Dilate_U0_p_dst_data_stream_0_V_write;
wire   [7:0] Dilate_U0_p_dst_data_stream_1_V_din;
wire    Dilate_U0_p_dst_data_stream_1_V_write;
wire   [7:0] Dilate_U0_p_dst_data_stream_2_V_din;
wire    Dilate_U0_p_dst_data_stream_2_V_write;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_2_V_read;
wire   [31:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;
wire    Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;
wire   [3:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;
wire   [3:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;
wire   [0:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;
wire   [0:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;
wire   [0:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TID;
wire   [0:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;
wire    ap_sync_continue;
wire    img_0_data_stream_0_full_n;
wire   [7:0] img_0_data_stream_0_dout;
wire    img_0_data_stream_0_empty_n;
wire    img_0_data_stream_1_full_n;
wire   [7:0] img_0_data_stream_1_dout;
wire    img_0_data_stream_1_empty_n;
wire    img_0_data_stream_2_full_n;
wire   [7:0] img_0_data_stream_2_dout;
wire    img_0_data_stream_2_empty_n;
wire    img_1_data_stream_0_full_n;
wire   [7:0] img_1_data_stream_0_dout;
wire    img_1_data_stream_0_empty_n;
wire    img_1_data_stream_1_full_n;
wire   [7:0] img_1_data_stream_1_dout;
wire    img_1_data_stream_1_empty_n;
wire    img_1_data_stream_2_full_n;
wire   [7:0] img_1_data_stream_2_dout;
wire    img_1_data_stream_2_empty_n;
wire    img_2_data_stream_0_full_n;
wire   [7:0] img_2_data_stream_0_dout;
wire    img_2_data_stream_0_empty_n;
wire    img_2_data_stream_1_full_n;
wire   [7:0] img_2_data_stream_1_dout;
wire    img_2_data_stream_1_empty_n;
wire    img_2_data_stream_2_full_n;
wire   [7:0] img_2_data_stream_2_dout;
wire    img_2_data_stream_2_empty_n;
wire    img_3_data_stream_0_full_n;
wire   [7:0] img_3_data_stream_0_dout;
wire    img_3_data_stream_0_empty_n;
wire    img_3_data_stream_1_full_n;
wire   [7:0] img_3_data_stream_1_dout;
wire    img_3_data_stream_1_empty_n;
wire    img_3_data_stream_2_full_n;
wire   [7:0] img_3_data_stream_2_dout;
wire    img_3_data_stream_2_empty_n;
wire    img_4_data_stream_0_full_n;
wire   [7:0] img_4_data_stream_0_dout;
wire    img_4_data_stream_0_empty_n;
wire    img_4_data_stream_1_full_n;
wire   [7:0] img_4_data_stream_1_dout;
wire    img_4_data_stream_1_empty_n;
wire    img_4_data_stream_2_full_n;
wire   [7:0] img_4_data_stream_2_dout;
wire    img_4_data_stream_2_empty_n;
wire    img_5_data_stream_0_full_n;
wire   [7:0] img_5_data_stream_0_dout;
wire    img_5_data_stream_0_empty_n;
wire    img_5_data_stream_1_full_n;
wire   [7:0] img_5_data_stream_1_dout;
wire    img_5_data_stream_1_empty_n;
wire    img_5_data_stream_2_full_n;
wire   [7:0] img_5_data_stream_2_dout;
wire    img_5_data_stream_2_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_Sobel_U0_din;
wire    start_for_Sobel_U0_full_n;
wire   [0:0] start_for_Sobel_U0_dout;
wire    start_for_Sobel_U0_empty_n;
wire   [0:0] start_for_SubS_U0_din;
wire    start_for_SubS_U0_full_n;
wire   [0:0] start_for_SubS_U0_dout;
wire    start_for_SubS_U0_empty_n;
wire   [0:0] start_for_Scale_U0_din;
wire    start_for_Scale_U0_full_n;
wire   [0:0] start_for_Scale_U0_dout;
wire    start_for_Scale_U0_empty_n;
wire   [0:0] start_for_Erode_U0_din;
wire    start_for_Erode_U0_full_n;
wire   [0:0] start_for_Erode_U0_dout;
wire    start_for_Erode_U0_empty_n;
wire   [0:0] start_for_Dilate_U0_din;
wire    start_for_Dilate_U0_full_n;
wire   [0:0] start_for_Dilate_U0_dout;
wire    start_for_Dilate_U0_empty_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_din;
wire    start_for_Mat2AXIvideo_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_dout;
wire    start_for_Mat2AXIvideo_U0_empty_n;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .start_full_n(start_for_Sobel_U0_full_n),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .start_out(AXIvideo2Mat_U0_start_out),
    .start_write(AXIvideo2Mat_U0_start_write),
    .INPUT_STREAM_TDATA(INPUT_STREAM_TDATA),
    .INPUT_STREAM_TVALID(INPUT_STREAM_TVALID),
    .INPUT_STREAM_TREADY(AXIvideo2Mat_U0_INPUT_STREAM_TREADY),
    .INPUT_STREAM_TKEEP(INPUT_STREAM_TKEEP),
    .INPUT_STREAM_TSTRB(INPUT_STREAM_TSTRB),
    .INPUT_STREAM_TUSER(INPUT_STREAM_TUSER),
    .INPUT_STREAM_TLAST(INPUT_STREAM_TLAST),
    .INPUT_STREAM_TID(INPUT_STREAM_TID),
    .INPUT_STREAM_TDEST(INPUT_STREAM_TDEST),
    .img_rows_V(rows),
    .img_cols_V(cols),
    .img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(img_0_data_stream_0_full_n),
    .img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(img_0_data_stream_1_full_n),
    .img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(img_0_data_stream_2_full_n),
    .img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write)
);

Sobel Sobel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Sobel_U0_ap_start),
    .start_full_n(start_for_SubS_U0_full_n),
    .ap_done(Sobel_U0_ap_done),
    .ap_continue(Sobel_U0_ap_continue),
    .ap_idle(Sobel_U0_ap_idle),
    .ap_ready(Sobel_U0_ap_ready),
    .start_out(Sobel_U0_start_out),
    .start_write(Sobel_U0_start_write),
    .p_src_rows_V(rows),
    .p_src_cols_V(cols),
    .p_src_data_stream_0_V_dout(img_0_data_stream_0_dout),
    .p_src_data_stream_0_V_empty_n(img_0_data_stream_0_empty_n),
    .p_src_data_stream_0_V_read(Sobel_U0_p_src_data_stream_0_V_read),
    .p_src_data_stream_1_V_dout(img_0_data_stream_1_dout),
    .p_src_data_stream_1_V_empty_n(img_0_data_stream_1_empty_n),
    .p_src_data_stream_1_V_read(Sobel_U0_p_src_data_stream_1_V_read),
    .p_src_data_stream_2_V_dout(img_0_data_stream_2_dout),
    .p_src_data_stream_2_V_empty_n(img_0_data_stream_2_empty_n),
    .p_src_data_stream_2_V_read(Sobel_U0_p_src_data_stream_2_V_read),
    .p_dst_data_stream_0_V_din(Sobel_U0_p_dst_data_stream_0_V_din),
    .p_dst_data_stream_0_V_full_n(img_1_data_stream_0_full_n),
    .p_dst_data_stream_0_V_write(Sobel_U0_p_dst_data_stream_0_V_write),
    .p_dst_data_stream_1_V_din(Sobel_U0_p_dst_data_stream_1_V_din),
    .p_dst_data_stream_1_V_full_n(img_1_data_stream_1_full_n),
    .p_dst_data_stream_1_V_write(Sobel_U0_p_dst_data_stream_1_V_write),
    .p_dst_data_stream_2_V_din(Sobel_U0_p_dst_data_stream_2_V_din),
    .p_dst_data_stream_2_V_full_n(img_1_data_stream_2_full_n),
    .p_dst_data_stream_2_V_write(Sobel_U0_p_dst_data_stream_2_V_write)
);

SubS SubS_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(SubS_U0_ap_start),
    .start_full_n(start_for_Scale_U0_full_n),
    .ap_done(SubS_U0_ap_done),
    .ap_continue(SubS_U0_ap_continue),
    .ap_idle(SubS_U0_ap_idle),
    .ap_ready(SubS_U0_ap_ready),
    .start_out(SubS_U0_start_out),
    .start_write(SubS_U0_start_write),
    .src_data_stream_0_V_dout(img_1_data_stream_0_dout),
    .src_data_stream_0_V_empty_n(img_1_data_stream_0_empty_n),
    .src_data_stream_0_V_read(SubS_U0_src_data_stream_0_V_read),
    .src_data_stream_1_V_dout(img_1_data_stream_1_dout),
    .src_data_stream_1_V_empty_n(img_1_data_stream_1_empty_n),
    .src_data_stream_1_V_read(SubS_U0_src_data_stream_1_V_read),
    .src_data_stream_2_V_dout(img_1_data_stream_2_dout),
    .src_data_stream_2_V_empty_n(img_1_data_stream_2_empty_n),
    .src_data_stream_2_V_read(SubS_U0_src_data_stream_2_V_read),
    .dst_rows_V(rows),
    .dst_cols_V(cols),
    .dst_data_stream_0_V_din(SubS_U0_dst_data_stream_0_V_din),
    .dst_data_stream_0_V_full_n(img_2_data_stream_0_full_n),
    .dst_data_stream_0_V_write(SubS_U0_dst_data_stream_0_V_write),
    .dst_data_stream_1_V_din(SubS_U0_dst_data_stream_1_V_din),
    .dst_data_stream_1_V_full_n(img_2_data_stream_1_full_n),
    .dst_data_stream_1_V_write(SubS_U0_dst_data_stream_1_V_write),
    .dst_data_stream_2_V_din(SubS_U0_dst_data_stream_2_V_din),
    .dst_data_stream_2_V_full_n(img_2_data_stream_2_full_n),
    .dst_data_stream_2_V_write(SubS_U0_dst_data_stream_2_V_write)
);

Scale Scale_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Scale_U0_ap_start),
    .start_full_n(start_for_Erode_U0_full_n),
    .ap_done(Scale_U0_ap_done),
    .ap_continue(Scale_U0_ap_continue),
    .ap_idle(Scale_U0_ap_idle),
    .ap_ready(Scale_U0_ap_ready),
    .start_out(Scale_U0_start_out),
    .start_write(Scale_U0_start_write),
    .src_data_stream_0_V_dout(img_2_data_stream_0_dout),
    .src_data_stream_0_V_empty_n(img_2_data_stream_0_empty_n),
    .src_data_stream_0_V_read(Scale_U0_src_data_stream_0_V_read),
    .src_data_stream_1_V_dout(img_2_data_stream_1_dout),
    .src_data_stream_1_V_empty_n(img_2_data_stream_1_empty_n),
    .src_data_stream_1_V_read(Scale_U0_src_data_stream_1_V_read),
    .src_data_stream_2_V_dout(img_2_data_stream_2_dout),
    .src_data_stream_2_V_empty_n(img_2_data_stream_2_empty_n),
    .src_data_stream_2_V_read(Scale_U0_src_data_stream_2_V_read),
    .dst_rows_V(rows),
    .dst_cols_V(cols),
    .dst_data_stream_0_V_din(Scale_U0_dst_data_stream_0_V_din),
    .dst_data_stream_0_V_full_n(img_3_data_stream_0_full_n),
    .dst_data_stream_0_V_write(Scale_U0_dst_data_stream_0_V_write),
    .dst_data_stream_1_V_din(Scale_U0_dst_data_stream_1_V_din),
    .dst_data_stream_1_V_full_n(img_3_data_stream_1_full_n),
    .dst_data_stream_1_V_write(Scale_U0_dst_data_stream_1_V_write),
    .dst_data_stream_2_V_din(Scale_U0_dst_data_stream_2_V_din),
    .dst_data_stream_2_V_full_n(img_3_data_stream_2_full_n),
    .dst_data_stream_2_V_write(Scale_U0_dst_data_stream_2_V_write)
);

Erode Erode_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Erode_U0_ap_start),
    .start_full_n(start_for_Dilate_U0_full_n),
    .ap_done(Erode_U0_ap_done),
    .ap_continue(Erode_U0_ap_continue),
    .ap_idle(Erode_U0_ap_idle),
    .ap_ready(Erode_U0_ap_ready),
    .start_out(Erode_U0_start_out),
    .start_write(Erode_U0_start_write),
    .p_src_rows_V(rows),
    .p_src_cols_V(cols),
    .p_src_data_stream_0_V_dout(img_3_data_stream_0_dout),
    .p_src_data_stream_0_V_empty_n(img_3_data_stream_0_empty_n),
    .p_src_data_stream_0_V_read(Erode_U0_p_src_data_stream_0_V_read),
    .p_src_data_stream_1_V_dout(img_3_data_stream_1_dout),
    .p_src_data_stream_1_V_empty_n(img_3_data_stream_1_empty_n),
    .p_src_data_stream_1_V_read(Erode_U0_p_src_data_stream_1_V_read),
    .p_src_data_stream_2_V_dout(img_3_data_stream_2_dout),
    .p_src_data_stream_2_V_empty_n(img_3_data_stream_2_empty_n),
    .p_src_data_stream_2_V_read(Erode_U0_p_src_data_stream_2_V_read),
    .p_dst_data_stream_0_V_din(Erode_U0_p_dst_data_stream_0_V_din),
    .p_dst_data_stream_0_V_full_n(img_4_data_stream_0_full_n),
    .p_dst_data_stream_0_V_write(Erode_U0_p_dst_data_stream_0_V_write),
    .p_dst_data_stream_1_V_din(Erode_U0_p_dst_data_stream_1_V_din),
    .p_dst_data_stream_1_V_full_n(img_4_data_stream_1_full_n),
    .p_dst_data_stream_1_V_write(Erode_U0_p_dst_data_stream_1_V_write),
    .p_dst_data_stream_2_V_din(Erode_U0_p_dst_data_stream_2_V_din),
    .p_dst_data_stream_2_V_full_n(img_4_data_stream_2_full_n),
    .p_dst_data_stream_2_V_write(Erode_U0_p_dst_data_stream_2_V_write)
);

Dilate Dilate_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Dilate_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .ap_done(Dilate_U0_ap_done),
    .ap_continue(Dilate_U0_ap_continue),
    .ap_idle(Dilate_U0_ap_idle),
    .ap_ready(Dilate_U0_ap_ready),
    .start_out(Dilate_U0_start_out),
    .start_write(Dilate_U0_start_write),
    .p_src_rows_V(rows),
    .p_src_cols_V(cols),
    .p_src_data_stream_0_V_dout(img_4_data_stream_0_dout),
    .p_src_data_stream_0_V_empty_n(img_4_data_stream_0_empty_n),
    .p_src_data_stream_0_V_read(Dilate_U0_p_src_data_stream_0_V_read),
    .p_src_data_stream_1_V_dout(img_4_data_stream_1_dout),
    .p_src_data_stream_1_V_empty_n(img_4_data_stream_1_empty_n),
    .p_src_data_stream_1_V_read(Dilate_U0_p_src_data_stream_1_V_read),
    .p_src_data_stream_2_V_dout(img_4_data_stream_2_dout),
    .p_src_data_stream_2_V_empty_n(img_4_data_stream_2_empty_n),
    .p_src_data_stream_2_V_read(Dilate_U0_p_src_data_stream_2_V_read),
    .p_dst_data_stream_0_V_din(Dilate_U0_p_dst_data_stream_0_V_din),
    .p_dst_data_stream_0_V_full_n(img_5_data_stream_0_full_n),
    .p_dst_data_stream_0_V_write(Dilate_U0_p_dst_data_stream_0_V_write),
    .p_dst_data_stream_1_V_din(Dilate_U0_p_dst_data_stream_1_V_din),
    .p_dst_data_stream_1_V_full_n(img_5_data_stream_1_full_n),
    .p_dst_data_stream_1_V_write(Dilate_U0_p_dst_data_stream_1_V_write),
    .p_dst_data_stream_2_V_din(Dilate_U0_p_dst_data_stream_2_V_din),
    .p_dst_data_stream_2_V_full_n(img_5_data_stream_2_full_n),
    .p_dst_data_stream_2_V_write(Dilate_U0_p_dst_data_stream_2_V_write)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_rows_V(rows),
    .img_cols_V(cols),
    .img_data_stream_0_V_dout(img_5_data_stream_0_dout),
    .img_data_stream_0_V_empty_n(img_5_data_stream_0_empty_n),
    .img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read),
    .img_data_stream_1_V_dout(img_5_data_stream_1_dout),
    .img_data_stream_1_V_empty_n(img_5_data_stream_1_empty_n),
    .img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read),
    .img_data_stream_2_V_dout(img_5_data_stream_2_dout),
    .img_data_stream_2_V_empty_n(img_5_data_stream_2_empty_n),
    .img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read),
    .OUTPUT_STREAM_TDATA(Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA),
    .OUTPUT_STREAM_TVALID(Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID),
    .OUTPUT_STREAM_TREADY(OUTPUT_STREAM_TREADY),
    .OUTPUT_STREAM_TKEEP(Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP),
    .OUTPUT_STREAM_TSTRB(Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB),
    .OUTPUT_STREAM_TUSER(Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER),
    .OUTPUT_STREAM_TLAST(Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST),
    .OUTPUT_STREAM_TID(Mat2AXIvideo_U0_OUTPUT_STREAM_TID),
    .OUTPUT_STREAM_TDEST(Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST)
);

fifo_w8_d2_A img_0_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .if_full_n(img_0_data_stream_0_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .if_dout(img_0_data_stream_0_dout),
    .if_empty_n(img_0_data_stream_0_empty_n),
    .if_read(Sobel_U0_p_src_data_stream_0_V_read)
);

fifo_w8_d2_A img_0_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .if_full_n(img_0_data_stream_1_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .if_dout(img_0_data_stream_1_dout),
    .if_empty_n(img_0_data_stream_1_empty_n),
    .if_read(Sobel_U0_p_src_data_stream_1_V_read)
);

fifo_w8_d2_A img_0_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .if_full_n(img_0_data_stream_2_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .if_dout(img_0_data_stream_2_dout),
    .if_empty_n(img_0_data_stream_2_empty_n),
    .if_read(Sobel_U0_p_src_data_stream_2_V_read)
);

fifo_w8_d2_A img_1_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_U0_p_dst_data_stream_0_V_din),
    .if_full_n(img_1_data_stream_0_full_n),
    .if_write(Sobel_U0_p_dst_data_stream_0_V_write),
    .if_dout(img_1_data_stream_0_dout),
    .if_empty_n(img_1_data_stream_0_empty_n),
    .if_read(SubS_U0_src_data_stream_0_V_read)
);

fifo_w8_d2_A img_1_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_U0_p_dst_data_stream_1_V_din),
    .if_full_n(img_1_data_stream_1_full_n),
    .if_write(Sobel_U0_p_dst_data_stream_1_V_write),
    .if_dout(img_1_data_stream_1_dout),
    .if_empty_n(img_1_data_stream_1_empty_n),
    .if_read(SubS_U0_src_data_stream_1_V_read)
);

fifo_w8_d2_A img_1_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_U0_p_dst_data_stream_2_V_din),
    .if_full_n(img_1_data_stream_2_full_n),
    .if_write(Sobel_U0_p_dst_data_stream_2_V_write),
    .if_dout(img_1_data_stream_2_dout),
    .if_empty_n(img_1_data_stream_2_empty_n),
    .if_read(SubS_U0_src_data_stream_2_V_read)
);

fifo_w8_d2_A img_2_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(SubS_U0_dst_data_stream_0_V_din),
    .if_full_n(img_2_data_stream_0_full_n),
    .if_write(SubS_U0_dst_data_stream_0_V_write),
    .if_dout(img_2_data_stream_0_dout),
    .if_empty_n(img_2_data_stream_0_empty_n),
    .if_read(Scale_U0_src_data_stream_0_V_read)
);

fifo_w8_d2_A img_2_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(SubS_U0_dst_data_stream_1_V_din),
    .if_full_n(img_2_data_stream_1_full_n),
    .if_write(SubS_U0_dst_data_stream_1_V_write),
    .if_dout(img_2_data_stream_1_dout),
    .if_empty_n(img_2_data_stream_1_empty_n),
    .if_read(Scale_U0_src_data_stream_1_V_read)
);

fifo_w8_d2_A img_2_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(SubS_U0_dst_data_stream_2_V_din),
    .if_full_n(img_2_data_stream_2_full_n),
    .if_write(SubS_U0_dst_data_stream_2_V_write),
    .if_dout(img_2_data_stream_2_dout),
    .if_empty_n(img_2_data_stream_2_empty_n),
    .if_read(Scale_U0_src_data_stream_2_V_read)
);

fifo_w8_d2_A img_3_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Scale_U0_dst_data_stream_0_V_din),
    .if_full_n(img_3_data_stream_0_full_n),
    .if_write(Scale_U0_dst_data_stream_0_V_write),
    .if_dout(img_3_data_stream_0_dout),
    .if_empty_n(img_3_data_stream_0_empty_n),
    .if_read(Erode_U0_p_src_data_stream_0_V_read)
);

fifo_w8_d2_A img_3_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Scale_U0_dst_data_stream_1_V_din),
    .if_full_n(img_3_data_stream_1_full_n),
    .if_write(Scale_U0_dst_data_stream_1_V_write),
    .if_dout(img_3_data_stream_1_dout),
    .if_empty_n(img_3_data_stream_1_empty_n),
    .if_read(Erode_U0_p_src_data_stream_1_V_read)
);

fifo_w8_d2_A img_3_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Scale_U0_dst_data_stream_2_V_din),
    .if_full_n(img_3_data_stream_2_full_n),
    .if_write(Scale_U0_dst_data_stream_2_V_write),
    .if_dout(img_3_data_stream_2_dout),
    .if_empty_n(img_3_data_stream_2_empty_n),
    .if_read(Erode_U0_p_src_data_stream_2_V_read)
);

fifo_w8_d2_A img_4_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Erode_U0_p_dst_data_stream_0_V_din),
    .if_full_n(img_4_data_stream_0_full_n),
    .if_write(Erode_U0_p_dst_data_stream_0_V_write),
    .if_dout(img_4_data_stream_0_dout),
    .if_empty_n(img_4_data_stream_0_empty_n),
    .if_read(Dilate_U0_p_src_data_stream_0_V_read)
);

fifo_w8_d2_A img_4_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Erode_U0_p_dst_data_stream_1_V_din),
    .if_full_n(img_4_data_stream_1_full_n),
    .if_write(Erode_U0_p_dst_data_stream_1_V_write),
    .if_dout(img_4_data_stream_1_dout),
    .if_empty_n(img_4_data_stream_1_empty_n),
    .if_read(Dilate_U0_p_src_data_stream_1_V_read)
);

fifo_w8_d2_A img_4_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Erode_U0_p_dst_data_stream_2_V_din),
    .if_full_n(img_4_data_stream_2_full_n),
    .if_write(Erode_U0_p_dst_data_stream_2_V_write),
    .if_dout(img_4_data_stream_2_dout),
    .if_empty_n(img_4_data_stream_2_empty_n),
    .if_read(Dilate_U0_p_src_data_stream_2_V_read)
);

fifo_w8_d2_A img_5_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Dilate_U0_p_dst_data_stream_0_V_din),
    .if_full_n(img_5_data_stream_0_full_n),
    .if_write(Dilate_U0_p_dst_data_stream_0_V_write),
    .if_dout(img_5_data_stream_0_dout),
    .if_empty_n(img_5_data_stream_0_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read)
);

fifo_w8_d2_A img_5_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Dilate_U0_p_dst_data_stream_1_V_din),
    .if_full_n(img_5_data_stream_1_full_n),
    .if_write(Dilate_U0_p_dst_data_stream_1_V_write),
    .if_dout(img_5_data_stream_1_dout),
    .if_empty_n(img_5_data_stream_1_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read)
);

fifo_w8_d2_A img_5_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Dilate_U0_p_dst_data_stream_2_V_din),
    .if_full_n(img_5_data_stream_2_full_n),
    .if_write(Dilate_U0_p_dst_data_stream_2_V_write),
    .if_dout(img_5_data_stream_2_dout),
    .if_empty_n(img_5_data_stream_2_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read)
);

start_for_Sobel_U0 start_for_Sobel_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_U0_din),
    .if_full_n(start_for_Sobel_U0_full_n),
    .if_write(AXIvideo2Mat_U0_start_write),
    .if_dout(start_for_Sobel_U0_dout),
    .if_empty_n(start_for_Sobel_U0_empty_n),
    .if_read(Sobel_U0_ap_ready)
);

start_for_SubS_U0 start_for_SubS_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_SubS_U0_din),
    .if_full_n(start_for_SubS_U0_full_n),
    .if_write(Sobel_U0_start_write),
    .if_dout(start_for_SubS_U0_dout),
    .if_empty_n(start_for_SubS_U0_empty_n),
    .if_read(SubS_U0_ap_ready)
);

start_for_Scale_U0 start_for_Scale_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Scale_U0_din),
    .if_full_n(start_for_Scale_U0_full_n),
    .if_write(SubS_U0_start_write),
    .if_dout(start_for_Scale_U0_dout),
    .if_empty_n(start_for_Scale_U0_empty_n),
    .if_read(Scale_U0_ap_ready)
);

start_for_Erode_U0 start_for_Erode_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Erode_U0_din),
    .if_full_n(start_for_Erode_U0_full_n),
    .if_write(Scale_U0_start_write),
    .if_dout(start_for_Erode_U0_dout),
    .if_empty_n(start_for_Erode_U0_empty_n),
    .if_read(Erode_U0_ap_ready)
);

start_for_Dilate_U0 start_for_Dilate_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Dilate_U0_din),
    .if_full_n(start_for_Dilate_U0_full_n),
    .if_write(Erode_U0_start_write),
    .if_dout(start_for_Dilate_U0_dout),
    .if_empty_n(start_for_Dilate_U0_empty_n),
    .if_read(Dilate_U0_ap_ready)
);

start_for_Mat2AXIudo start_for_Mat2AXIudo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .if_write(Dilate_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_U0_empty_n),
    .if_read(Mat2AXIvideo_U0_ap_ready)
);

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = ap_start;

assign Dilate_U0_ap_continue = 1'b1;

assign Dilate_U0_ap_start = start_for_Dilate_U0_empty_n;

assign Erode_U0_ap_continue = 1'b1;

assign Erode_U0_ap_start = start_for_Erode_U0_empty_n;

assign INPUT_STREAM_TREADY = AXIvideo2Mat_U0_INPUT_STREAM_TREADY;

assign Mat2AXIvideo_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign OUTPUT_STREAM_TDATA = Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;

assign OUTPUT_STREAM_TDEST = Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;

assign OUTPUT_STREAM_TID = Mat2AXIvideo_U0_OUTPUT_STREAM_TID;

assign OUTPUT_STREAM_TKEEP = Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;

assign OUTPUT_STREAM_TLAST = Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;

assign OUTPUT_STREAM_TSTRB = Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;

assign OUTPUT_STREAM_TUSER = Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;

assign OUTPUT_STREAM_TVALID = Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;

assign Scale_U0_ap_continue = 1'b1;

assign Scale_U0_ap_start = start_for_Scale_U0_empty_n;

assign Sobel_U0_ap_continue = 1'b1;

assign Sobel_U0_ap_start = start_for_Sobel_U0_empty_n;

assign SubS_U0_ap_continue = 1'b1;

assign SubS_U0_ap_start = start_for_SubS_U0_empty_n;

assign ap_done = Mat2AXIvideo_U0_ap_done;

assign ap_idle = (SubS_U0_ap_idle & Sobel_U0_ap_idle & Scale_U0_ap_idle & Mat2AXIvideo_U0_ap_idle & Erode_U0_ap_idle & Dilate_U0_ap_idle & AXIvideo2Mat_U0_ap_idle);

assign ap_ready = AXIvideo2Mat_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Mat2AXIvideo_U0_ap_done;

assign ap_sync_ready = AXIvideo2Mat_U0_ap_ready;

assign start_for_Dilate_U0_din = 1'b1;

assign start_for_Erode_U0_din = 1'b1;

assign start_for_Mat2AXIvideo_U0_din = 1'b1;

assign start_for_Scale_U0_din = 1'b1;

assign start_for_Sobel_U0_din = 1'b1;

assign start_for_SubS_U0_din = 1'b1;

endmodule //hls_sobel
