// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Dilate.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Dilate::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Dilate::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> Dilate::ap_ST_fsm_state1 = "1";
const sc_lv<4> Dilate::ap_ST_fsm_state2 = "10";
const sc_lv<4> Dilate::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> Dilate::ap_ST_fsm_state6 = "1000";
const sc_lv<32> Dilate::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Dilate::ap_const_boolean_1 = true;
const sc_lv<32> Dilate::ap_const_lv32_2 = "10";
const bool Dilate::ap_const_boolean_0 = false;
const sc_lv<1> Dilate::ap_const_lv1_1 = "1";
const sc_lv<1> Dilate::ap_const_lv1_0 = "0";
const sc_lv<32> Dilate::ap_const_lv32_1 = "1";
const sc_lv<32> Dilate::ap_const_lv32_3 = "11";
const sc_lv<32> Dilate::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> Dilate::ap_const_lv32_1F = "11111";
const sc_lv<31> Dilate::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> Dilate::ap_const_lv32_FFFFFFFE = "11111111111111111111111111111110";
const sc_lv<32> Dilate::ap_const_lv32_FFFFFFFD = "11111111111111111111111111111101";
const sc_lv<8> Dilate::ap_const_lv8_0 = "00000000";

Dilate::Dilate(sc_module_name name) : sc_module(name), mVcdFile(0) {
    k_buf_0_val_3_U = new FAST_t_opr_k_buf_eOg("k_buf_0_val_3_U");
    k_buf_0_val_3_U->clk(ap_clk);
    k_buf_0_val_3_U->reset(ap_rst);
    k_buf_0_val_3_U->address0(k_buf_0_val_3_address0);
    k_buf_0_val_3_U->ce0(k_buf_0_val_3_ce0);
    k_buf_0_val_3_U->q0(k_buf_0_val_3_q0);
    k_buf_0_val_3_U->address1(k_buf_0_val_3_address1);
    k_buf_0_val_3_U->ce1(k_buf_0_val_3_ce1);
    k_buf_0_val_3_U->we1(k_buf_0_val_3_we1);
    k_buf_0_val_3_U->d1(p_src_data_stream_V_dout);
    k_buf_0_val_4_U = new FAST_t_opr_k_buf_eOg("k_buf_0_val_4_U");
    k_buf_0_val_4_U->clk(ap_clk);
    k_buf_0_val_4_U->reset(ap_rst);
    k_buf_0_val_4_U->address0(k_buf_0_val_4_address0);
    k_buf_0_val_4_U->ce0(k_buf_0_val_4_ce0);
    k_buf_0_val_4_U->q0(k_buf_0_val_4_q0);
    k_buf_0_val_4_U->address1(k_buf_0_val_4_address1);
    k_buf_0_val_4_U->ce1(k_buf_0_val_4_ce1);
    k_buf_0_val_4_U->we1(k_buf_0_val_4_we1);
    k_buf_0_val_4_U->d1(k_buf_0_val_4_d1);
    k_buf_0_val_5_U = new FAST_t_opr_k_buf_eOg("k_buf_0_val_5_U");
    k_buf_0_val_5_U->clk(ap_clk);
    k_buf_0_val_5_U->reset(ap_rst);
    k_buf_0_val_5_U->address0(k_buf_0_val_5_address0);
    k_buf_0_val_5_U->ce0(k_buf_0_val_5_ce0);
    k_buf_0_val_5_U->q0(k_buf_0_val_5_q0);
    k_buf_0_val_5_U->address1(k_buf_0_val_5_address1);
    k_buf_0_val_5_U->ce1(k_buf_0_val_5_ce1);
    k_buf_0_val_5_U->we1(k_buf_0_val_5_we1);
    k_buf_0_val_5_U->d1(k_buf_0_val_5_d1);
    hls_fast_corner_mpcA_U48 = new hls_fast_corner_mpcA<1,1,8,8,8,2,8>("hls_fast_corner_mpcA_U48");
    hls_fast_corner_mpcA_U48->din0(right_border_buf_0_s_fu_156);
    hls_fast_corner_mpcA_U48->din1(ap_var_for_const0);
    hls_fast_corner_mpcA_U48->din2(ap_var_for_const0);
    hls_fast_corner_mpcA_U48->din3(tmp_56_reg_1128);
    hls_fast_corner_mpcA_U48->dout(tmp_30_fu_664_p5);
    hls_fast_corner_mpcA_U49 = new hls_fast_corner_mpcA<1,1,8,8,8,2,8>("hls_fast_corner_mpcA_U49");
    hls_fast_corner_mpcA_U49->din0(right_border_buf_0_2_fu_164);
    hls_fast_corner_mpcA_U49->din1(ap_var_for_const0);
    hls_fast_corner_mpcA_U49->din2(ap_var_for_const0);
    hls_fast_corner_mpcA_U49->din3(tmp_56_reg_1128);
    hls_fast_corner_mpcA_U49->dout(tmp_31_fu_682_p5);
    hls_fast_corner_mpcA_U50 = new hls_fast_corner_mpcA<1,1,8,8,8,2,8>("hls_fast_corner_mpcA_U50");
    hls_fast_corner_mpcA_U50->din0(right_border_buf_0_1_fu_160);
    hls_fast_corner_mpcA_U50->din1(ap_var_for_const0);
    hls_fast_corner_mpcA_U50->din2(ap_var_for_const0);
    hls_fast_corner_mpcA_U50->din3(tmp_56_reg_1128);
    hls_fast_corner_mpcA_U50->dout(tmp_32_fu_700_p5);
    hls_fast_corner_mpcA_U51 = new hls_fast_corner_mpcA<1,1,8,8,8,2,8>("hls_fast_corner_mpcA_U51");
    hls_fast_corner_mpcA_U51->din0(col_buf_0_val_0_0_fu_675_p3);
    hls_fast_corner_mpcA_U51->din1(col_buf_0_val_1_0_fu_693_p3);
    hls_fast_corner_mpcA_U51->din2(col_buf_0_val_2_0_fu_711_p3);
    hls_fast_corner_mpcA_U51->din3(tmp_50_reg_1087);
    hls_fast_corner_mpcA_U51->dout(tmp_33_fu_733_p5);
    hls_fast_corner_mpcA_U52 = new hls_fast_corner_mpcA<1,1,8,8,8,2,8>("hls_fast_corner_mpcA_U52");
    hls_fast_corner_mpcA_U52->din0(col_buf_0_val_0_0_fu_675_p3);
    hls_fast_corner_mpcA_U52->din1(col_buf_0_val_1_0_fu_693_p3);
    hls_fast_corner_mpcA_U52->din2(col_buf_0_val_2_0_fu_711_p3);
    hls_fast_corner_mpcA_U52->din3(tmp_51_reg_1092);
    hls_fast_corner_mpcA_U52->dout(tmp_34_fu_751_p5);
    hls_fast_corner_mpcA_U53 = new hls_fast_corner_mpcA<1,1,8,8,8,2,8>("hls_fast_corner_mpcA_U53");
    hls_fast_corner_mpcA_U53->din0(col_buf_0_val_0_0_fu_675_p3);
    hls_fast_corner_mpcA_U53->din1(col_buf_0_val_1_0_fu_693_p3);
    hls_fast_corner_mpcA_U53->din2(col_buf_0_val_2_0_fu_711_p3);
    hls_fast_corner_mpcA_U53->din3(tmp_52_reg_1097);
    hls_fast_corner_mpcA_U53->dout(tmp_35_fu_769_p5);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ImagLoc_x_fu_575_p2);
    sensitive << ( t_V_5_reg_269 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );
    sensitive << ( ap_predicate_op125_read_state4 );
    sensitive << ( ap_predicate_op133_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );
    sensitive << ( ap_predicate_op125_read_state4 );
    sensitive << ( ap_predicate_op133_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );
    sensitive << ( ap_predicate_op125_read_state4 );
    sensitive << ( ap_predicate_op133_read_state4 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( ap_predicate_op125_read_state4 );
    sensitive << ( ap_predicate_op133_read_state4 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );

    SC_METHOD(thread_ap_condition_734);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_1111 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( exitcond460_i_i_fu_548_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_operation_102);
    sensitive << ( exitcond460_i_i_fu_548_p2 );

    SC_METHOD(thread_ap_enable_operation_104);
    sensitive << ( exitcond460_i_i_fu_548_p2 );

    SC_METHOD(thread_ap_enable_operation_116);

    SC_METHOD(thread_ap_enable_operation_119);

    SC_METHOD(thread_ap_enable_operation_122);

    SC_METHOD(thread_ap_enable_operation_126);
    sensitive << ( ap_predicate_op126_store_state4 );

    SC_METHOD(thread_ap_enable_operation_127);
    sensitive << ( ap_predicate_op127_store_state4 );

    SC_METHOD(thread_ap_enable_operation_129);
    sensitive << ( ap_predicate_op129_store_state4 );

    SC_METHOD(thread_ap_enable_operation_131);
    sensitive << ( ap_predicate_op131_store_state4 );

    SC_METHOD(thread_ap_enable_operation_132);
    sensitive << ( ap_predicate_op132_store_state4 );

    SC_METHOD(thread_ap_enable_operation_134);
    sensitive << ( ap_predicate_op134_store_state4 );

    SC_METHOD(thread_ap_enable_operation_99);
    sensitive << ( exitcond460_i_i_fu_548_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_state3_pp0_iter0_stage0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_enable_state4_pp0_iter1_stage0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_predicate_op125_read_state4);
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );

    SC_METHOD(thread_ap_predicate_op126_store_state4);
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_23_reg_1072 );

    SC_METHOD(thread_ap_predicate_op127_store_state4);
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_23_reg_1072 );

    SC_METHOD(thread_ap_predicate_op129_store_state4);
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_167_2_reg_1076 );

    SC_METHOD(thread_ap_predicate_op131_store_state4);
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );

    SC_METHOD(thread_ap_predicate_op132_store_state4);
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );

    SC_METHOD(thread_ap_predicate_op133_read_state4);
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );

    SC_METHOD(thread_ap_predicate_op134_store_state4);
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_brmerge_fu_634_p2);
    sensitive << ( tmp_137_not_reg_1062 );
    sensitive << ( tmp_28_fu_595_p2 );

    SC_METHOD(thread_col_assign_1_fu_629_p2);
    sensitive << ( tmp_19_fu_292_p2 );
    sensitive << ( x_fu_621_p3 );

    SC_METHOD(thread_col_buf_0_val_0_0_fu_675_p3);
    sensitive << ( brmerge_reg_1115 );
    sensitive << ( k_buf_0_val_3_q0 );
    sensitive << ( tmp_30_fu_664_p5 );

    SC_METHOD(thread_col_buf_0_val_1_0_fu_693_p3);
    sensitive << ( brmerge_reg_1115 );
    sensitive << ( k_buf_0_val_4_q0 );
    sensitive << ( tmp_31_fu_682_p5 );

    SC_METHOD(thread_col_buf_0_val_2_0_fu_711_p3);
    sensitive << ( brmerge_reg_1115 );
    sensitive << ( k_buf_0_val_5_q0 );
    sensitive << ( tmp_32_fu_700_p5 );

    SC_METHOD(thread_exitcond460_i_i_fu_548_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_5_reg_269 );
    sensitive << ( tmp_s_fu_280_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond461_i_i_fu_304_p2);
    sensitive << ( tmp_18_fu_286_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_i_V_fu_309_p2);
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_icmp2_fu_569_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond460_i_i_fu_548_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_53_fu_559_p4 );

    SC_METHOD(thread_icmp_fu_336_p2);
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_326_p4 );

    SC_METHOD(thread_j_V_fu_553_p2);
    sensitive << ( t_V_5_reg_269 );

    SC_METHOD(thread_k_buf_0_val_3_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_29_fu_639_p1 );

    SC_METHOD(thread_k_buf_0_val_3_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_167_2_reg_1076 );
    sensitive << ( k_buf_0_val_3_addr_reg_1122 );

    SC_METHOD(thread_k_buf_0_val_3_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_k_buf_0_val_3_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_167_2_reg_1076 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_3_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_167_2_reg_1076 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_4_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_29_fu_639_p1 );

    SC_METHOD(thread_k_buf_0_val_4_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_23_reg_1072 );
    sensitive << ( k_buf_0_val_4_addr_reg_1135 );

    SC_METHOD(thread_k_buf_0_val_4_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_k_buf_0_val_4_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_23_reg_1072 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_4_d1);
    sensitive << ( p_src_data_stream_V_dout );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_23_reg_1072 );
    sensitive << ( k_buf_0_val_3_q0 );
    sensitive << ( ap_condition_734 );

    SC_METHOD(thread_k_buf_0_val_4_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_23_reg_1072 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_5_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_29_fu_639_p1 );

    SC_METHOD(thread_k_buf_0_val_5_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_23_reg_1072 );
    sensitive << ( k_buf_0_val_5_addr_reg_1141 );

    SC_METHOD(thread_k_buf_0_val_5_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_k_buf_0_val_5_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_23_reg_1072 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_5_d1);
    sensitive << ( p_src_data_stream_V_dout );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_23_reg_1072 );
    sensitive << ( k_buf_0_val_4_q0 );
    sensitive << ( ap_condition_734 );

    SC_METHOD(thread_k_buf_0_val_5_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );
    sensitive << ( tmp_23_reg_1072 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_or_cond_i495_i_i_1_fu_430_p2);
    sensitive << ( tmp_194_1_fu_425_p2 );
    sensitive << ( rev1_fu_419_p2 );

    SC_METHOD(thread_or_cond_i495_i_i_2_fu_476_p2);
    sensitive << ( tmp_194_2_fu_471_p2 );
    sensitive << ( rev2_fu_465_p2 );

    SC_METHOD(thread_or_cond_i495_i_i_fu_384_p2);
    sensitive << ( tmp_26_fu_379_p2 );
    sensitive << ( rev_fu_373_p2 );

    SC_METHOD(thread_or_cond_i_i_fu_650_p2);
    sensitive << ( icmp_reg_1067 );
    sensitive << ( icmp2_fu_569_p2 );

    SC_METHOD(thread_or_cond_i_i_i_fu_600_p2);
    sensitive << ( tmp_28_fu_595_p2 );
    sensitive << ( rev3_fu_589_p2 );

    SC_METHOD(thread_p_assign_1_fu_614_p3);
    sensitive << ( tmp_19_fu_292_p2 );
    sensitive << ( tmp_55_fu_606_p3 );

    SC_METHOD(thread_p_assign_4_1_fu_405_p2);
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_p_assign_4_2_fu_451_p2);
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_p_assign_5_1_fu_444_p3);
    sensitive << ( p_neg465_i_i_fu_298_p2 );
    sensitive << ( tmp_47_fu_436_p3 );

    SC_METHOD(thread_p_assign_5_2_fu_490_p3);
    sensitive << ( p_neg465_i_i_fu_298_p2 );
    sensitive << ( tmp_49_fu_482_p3 );

    SC_METHOD(thread_p_assign_5_fu_398_p3);
    sensitive << ( p_neg465_i_i_fu_298_p2 );
    sensitive << ( tmp_45_fu_390_p3 );

    SC_METHOD(thread_p_dst_data_stream_V_blk_n);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );

    SC_METHOD(thread_p_dst_data_stream_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );
    sensitive << ( src_kernel_win_0_va_6_reg_1151 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( temp_0_i_i_i_0210_i_6_fu_919_p3 );
    sensitive << ( tmp_213_2_2_fu_927_p2 );

    SC_METHOD(thread_p_dst_data_stream_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_neg465_i_i_fu_298_p2);
    sensitive << ( p_src_rows_V );

    SC_METHOD(thread_p_src_data_stream_V_blk_n);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_1111 );
    sensitive << ( icmp_reg_1067 );
    sensitive << ( tmp_21_reg_1058 );

    SC_METHOD(thread_p_src_data_stream_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op125_read_state4 );
    sensitive << ( ap_predicate_op133_read_state4 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_rev1_fu_419_p2);
    sensitive << ( tmp_46_fu_411_p3 );

    SC_METHOD(thread_rev2_fu_465_p2);
    sensitive << ( tmp_48_fu_457_p3 );

    SC_METHOD(thread_rev3_fu_589_p2);
    sensitive << ( tmp_54_fu_581_p3 );

    SC_METHOD(thread_rev_fu_373_p2);
    sensitive << ( tmp_44_fu_365_p3 );

    SC_METHOD(thread_row_assign_7_1_fu_522_p2);
    sensitive << ( p_neg465_i_i_fu_298_p2 );
    sensitive << ( y_1_fu_514_p3 );

    SC_METHOD(thread_row_assign_7_2_fu_539_p2);
    sensitive << ( p_neg465_i_i_fu_298_p2 );
    sensitive << ( y_2_fu_531_p3 );

    SC_METHOD(thread_row_assign_7_fu_505_p2);
    sensitive << ( p_neg465_i_i_fu_298_p2 );
    sensitive << ( y_fu_497_p3 );

    SC_METHOD(thread_src_kernel_win_0_va_6_fu_744_p3);
    sensitive << ( tmp_24_reg_1080 );
    sensitive << ( col_buf_0_val_0_0_fu_675_p3 );
    sensitive << ( tmp_33_fu_733_p5 );

    SC_METHOD(thread_src_kernel_win_0_va_7_fu_762_p3);
    sensitive << ( tmp_24_reg_1080 );
    sensitive << ( col_buf_0_val_1_0_fu_693_p3 );
    sensitive << ( tmp_34_fu_751_p5 );

    SC_METHOD(thread_src_kernel_win_0_va_8_fu_780_p3);
    sensitive << ( tmp_24_reg_1080 );
    sensitive << ( col_buf_0_val_2_0_fu_711_p3 );
    sensitive << ( tmp_35_fu_769_p5 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_1_fu_819_p3);
    sensitive << ( src_kernel_win_0_va_8_fu_780_p3 );
    sensitive << ( temp_0_i_i_i_0210_i_fu_805_p3 );
    sensitive << ( tmp_213_0_2_fu_813_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_2_fu_833_p3);
    sensitive << ( src_kernel_win_0_va_3_fu_144 );
    sensitive << ( temp_0_i_i_i_0210_i_1_fu_819_p3 );
    sensitive << ( tmp_213_1_fu_827_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_3_fu_847_p3);
    sensitive << ( src_kernel_win_0_va_2_fu_140 );
    sensitive << ( temp_0_i_i_i_0210_i_2_fu_833_p3 );
    sensitive << ( tmp_213_1_1_fu_841_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_4_fu_861_p3);
    sensitive << ( src_kernel_win_0_va_7_fu_762_p3 );
    sensitive << ( temp_0_i_i_i_0210_i_3_fu_847_p3 );
    sensitive << ( tmp_213_1_2_fu_855_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_5_fu_906_p3);
    sensitive << ( temp_0_i_i_i_0210_i_4_reg_1158 );
    sensitive << ( src_kernel_win_0_va_1_fu_136 );
    sensitive << ( tmp_213_2_fu_901_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_6_fu_919_p3);
    sensitive << ( src_kernel_win_0_va_fu_132 );
    sensitive << ( temp_0_i_i_i_0210_i_5_fu_906_p3 );
    sensitive << ( tmp_213_2_1_fu_913_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_fu_805_p3);
    sensitive << ( src_kernel_win_0_va_4_fu_148 );
    sensitive << ( src_kernel_win_0_va_5_fu_152 );
    sensitive << ( tmp_213_0_1_fu_799_p2 );

    SC_METHOD(thread_tmp_137_not_fu_320_p2);
    sensitive << ( tmp_21_fu_315_p2 );

    SC_METHOD(thread_tmp_167_2_fu_348_p2);
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_tmp_18_fu_286_p2);
    sensitive << ( p_src_rows_V );

    SC_METHOD(thread_tmp_194_1_fu_425_p2);
    sensitive << ( p_src_rows_V );
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_assign_4_1_fu_405_p2 );

    SC_METHOD(thread_tmp_194_2_fu_471_p2);
    sensitive << ( p_src_rows_V );
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_assign_4_2_fu_451_p2 );

    SC_METHOD(thread_tmp_19_fu_292_p2);
    sensitive << ( p_src_cols_V );

    SC_METHOD(thread_tmp_213_0_1_fu_799_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_reg_1147 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_4_fu_148 );
    sensitive << ( src_kernel_win_0_va_5_fu_152 );

    SC_METHOD(thread_tmp_213_0_2_fu_813_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_reg_1147 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_8_fu_780_p3 );
    sensitive << ( temp_0_i_i_i_0210_i_fu_805_p3 );

    SC_METHOD(thread_tmp_213_1_1_fu_841_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_reg_1147 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_2_fu_140 );
    sensitive << ( temp_0_i_i_i_0210_i_2_fu_833_p3 );

    SC_METHOD(thread_tmp_213_1_2_fu_855_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_reg_1147 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_7_fu_762_p3 );
    sensitive << ( temp_0_i_i_i_0210_i_3_fu_847_p3 );

    SC_METHOD(thread_tmp_213_1_fu_827_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_reg_1147 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_3_fu_144 );
    sensitive << ( temp_0_i_i_i_0210_i_1_fu_819_p3 );

    SC_METHOD(thread_tmp_213_2_1_fu_913_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_fu_132 );
    sensitive << ( temp_0_i_i_i_0210_i_5_fu_906_p3 );

    SC_METHOD(thread_tmp_213_2_2_fu_927_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_6_reg_1151 );
    sensitive << ( temp_0_i_i_i_0210_i_6_fu_919_p3 );

    SC_METHOD(thread_tmp_213_2_fu_901_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( or_cond_i_i_reg_1147_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( temp_0_i_i_i_0210_i_4_reg_1158 );
    sensitive << ( src_kernel_win_0_va_1_fu_136 );

    SC_METHOD(thread_tmp_21_fu_315_p2);
    sensitive << ( p_src_rows_V );
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_tmp_23_fu_342_p2);
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_tmp_24_fu_354_p2);
    sensitive << ( p_src_rows_V );
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_tmp_25_fu_359_p2);
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_tmp_26_fu_379_p2);
    sensitive << ( p_src_rows_V );
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_25_fu_359_p2 );

    SC_METHOD(thread_tmp_28_fu_595_p2);
    sensitive << ( p_src_cols_V );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond460_i_i_fu_548_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ImagLoc_x_fu_575_p2 );

    SC_METHOD(thread_tmp_29_fu_639_p1);
    sensitive << ( x_fu_621_p3 );

    SC_METHOD(thread_tmp_44_fu_365_p3);
    sensitive << ( tmp_25_fu_359_p2 );

    SC_METHOD(thread_tmp_45_fu_390_p3);
    sensitive << ( tmp_25_fu_359_p2 );

    SC_METHOD(thread_tmp_46_fu_411_p3);
    sensitive << ( p_assign_4_1_fu_405_p2 );

    SC_METHOD(thread_tmp_47_fu_436_p3);
    sensitive << ( p_assign_4_1_fu_405_p2 );

    SC_METHOD(thread_tmp_48_fu_457_p3);
    sensitive << ( p_assign_4_2_fu_451_p2 );

    SC_METHOD(thread_tmp_49_fu_482_p3);
    sensitive << ( p_assign_4_2_fu_451_p2 );

    SC_METHOD(thread_tmp_50_fu_510_p1);
    sensitive << ( row_assign_7_fu_505_p2 );

    SC_METHOD(thread_tmp_51_fu_527_p1);
    sensitive << ( row_assign_7_1_fu_522_p2 );

    SC_METHOD(thread_tmp_52_fu_544_p1);
    sensitive << ( row_assign_7_2_fu_539_p2 );

    SC_METHOD(thread_tmp_53_fu_559_p4);
    sensitive << ( t_V_5_reg_269 );

    SC_METHOD(thread_tmp_54_fu_581_p3);
    sensitive << ( ImagLoc_x_fu_575_p2 );

    SC_METHOD(thread_tmp_55_fu_606_p3);
    sensitive << ( ImagLoc_x_fu_575_p2 );

    SC_METHOD(thread_tmp_56_fu_646_p1);
    sensitive << ( col_assign_1_fu_629_p2 );

    SC_METHOD(thread_tmp_fu_326_p4);
    sensitive << ( t_V_reg_258 );

    SC_METHOD(thread_tmp_s_fu_280_p2);
    sensitive << ( p_src_cols_V );

    SC_METHOD(thread_x_fu_621_p3);
    sensitive << ( or_cond_i_i_i_fu_600_p2 );
    sensitive << ( ImagLoc_x_fu_575_p2 );
    sensitive << ( p_assign_1_fu_614_p3 );

    SC_METHOD(thread_y_1_fu_514_p3);
    sensitive << ( p_assign_4_1_fu_405_p2 );
    sensitive << ( or_cond_i495_i_i_1_fu_430_p2 );
    sensitive << ( p_assign_5_1_fu_444_p3 );

    SC_METHOD(thread_y_2_fu_531_p3);
    sensitive << ( p_assign_4_2_fu_451_p2 );
    sensitive << ( or_cond_i495_i_i_2_fu_476_p2 );
    sensitive << ( p_assign_5_2_fu_490_p3 );

    SC_METHOD(thread_y_fu_497_p3);
    sensitive << ( tmp_25_fu_359_p2 );
    sensitive << ( or_cond_i495_i_i_fu_384_p2 );
    sensitive << ( p_assign_5_fu_398_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond461_i_i_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond460_i_i_fu_548_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Dilate_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_rows_V, "(port)p_src_rows_V");
    sc_trace(mVcdFile, p_src_cols_V, "(port)p_src_cols_V");
    sc_trace(mVcdFile, p_src_data_stream_V_dout, "(port)p_src_data_stream_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_V_empty_n, "(port)p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_V_read, "(port)p_src_data_stream_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_V_din, "(port)p_dst_data_stream_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_V_full_n, "(port)p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_write, "(port)p_dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_src_data_stream_V_blk_n, "p_src_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, or_cond_i_i_i_reg_1111, "or_cond_i_i_i_reg_1111");
    sc_trace(mVcdFile, icmp_reg_1067, "icmp_reg_1067");
    sc_trace(mVcdFile, tmp_21_reg_1058, "tmp_21_reg_1058");
    sc_trace(mVcdFile, p_dst_data_stream_V_blk_n, "p_dst_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, or_cond_i_i_reg_1147, "or_cond_i_i_reg_1147");
    sc_trace(mVcdFile, or_cond_i_i_reg_1147_pp0_iter1_reg, "or_cond_i_i_reg_1147_pp0_iter1_reg");
    sc_trace(mVcdFile, t_V_5_reg_269, "t_V_5_reg_269");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, tmp_s_fu_280_p2, "tmp_s_fu_280_p2");
    sc_trace(mVcdFile, tmp_18_fu_286_p2, "tmp_18_fu_286_p2");
    sc_trace(mVcdFile, tmp_19_fu_292_p2, "tmp_19_fu_292_p2");
    sc_trace(mVcdFile, p_neg465_i_i_fu_298_p2, "p_neg465_i_i_fu_298_p2");
    sc_trace(mVcdFile, exitcond461_i_i_fu_304_p2, "exitcond461_i_i_fu_304_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_V_fu_309_p2, "i_V_fu_309_p2");
    sc_trace(mVcdFile, i_V_reg_1053, "i_V_reg_1053");
    sc_trace(mVcdFile, tmp_21_fu_315_p2, "tmp_21_fu_315_p2");
    sc_trace(mVcdFile, tmp_137_not_fu_320_p2, "tmp_137_not_fu_320_p2");
    sc_trace(mVcdFile, tmp_137_not_reg_1062, "tmp_137_not_reg_1062");
    sc_trace(mVcdFile, icmp_fu_336_p2, "icmp_fu_336_p2");
    sc_trace(mVcdFile, tmp_23_fu_342_p2, "tmp_23_fu_342_p2");
    sc_trace(mVcdFile, tmp_23_reg_1072, "tmp_23_reg_1072");
    sc_trace(mVcdFile, tmp_167_2_fu_348_p2, "tmp_167_2_fu_348_p2");
    sc_trace(mVcdFile, tmp_167_2_reg_1076, "tmp_167_2_reg_1076");
    sc_trace(mVcdFile, tmp_24_fu_354_p2, "tmp_24_fu_354_p2");
    sc_trace(mVcdFile, tmp_24_reg_1080, "tmp_24_reg_1080");
    sc_trace(mVcdFile, tmp_50_fu_510_p1, "tmp_50_fu_510_p1");
    sc_trace(mVcdFile, tmp_50_reg_1087, "tmp_50_reg_1087");
    sc_trace(mVcdFile, tmp_51_fu_527_p1, "tmp_51_fu_527_p1");
    sc_trace(mVcdFile, tmp_51_reg_1092, "tmp_51_reg_1092");
    sc_trace(mVcdFile, tmp_52_fu_544_p1, "tmp_52_fu_544_p1");
    sc_trace(mVcdFile, tmp_52_reg_1097, "tmp_52_reg_1097");
    sc_trace(mVcdFile, exitcond460_i_i_fu_548_p2, "exitcond460_i_i_fu_548_p2");
    sc_trace(mVcdFile, exitcond460_i_i_reg_1102, "exitcond460_i_i_reg_1102");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_predicate_op125_read_state4, "ap_predicate_op125_read_state4");
    sc_trace(mVcdFile, ap_predicate_op133_read_state4, "ap_predicate_op133_read_state4");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond460_i_i_reg_1102_pp0_iter1_reg, "exitcond460_i_i_reg_1102_pp0_iter1_reg");
    sc_trace(mVcdFile, j_V_fu_553_p2, "j_V_fu_553_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, or_cond_i_i_i_fu_600_p2, "or_cond_i_i_i_fu_600_p2");
    sc_trace(mVcdFile, brmerge_fu_634_p2, "brmerge_fu_634_p2");
    sc_trace(mVcdFile, brmerge_reg_1115, "brmerge_reg_1115");
    sc_trace(mVcdFile, k_buf_0_val_3_addr_reg_1122, "k_buf_0_val_3_addr_reg_1122");
    sc_trace(mVcdFile, tmp_56_fu_646_p1, "tmp_56_fu_646_p1");
    sc_trace(mVcdFile, tmp_56_reg_1128, "tmp_56_reg_1128");
    sc_trace(mVcdFile, k_buf_0_val_4_addr_reg_1135, "k_buf_0_val_4_addr_reg_1135");
    sc_trace(mVcdFile, k_buf_0_val_5_addr_reg_1141, "k_buf_0_val_5_addr_reg_1141");
    sc_trace(mVcdFile, or_cond_i_i_fu_650_p2, "or_cond_i_i_fu_650_p2");
    sc_trace(mVcdFile, src_kernel_win_0_va_6_fu_744_p3, "src_kernel_win_0_va_6_fu_744_p3");
    sc_trace(mVcdFile, src_kernel_win_0_va_6_reg_1151, "src_kernel_win_0_va_6_reg_1151");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_4_fu_861_p3, "temp_0_i_i_i_0210_i_4_fu_861_p3");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_4_reg_1158, "temp_0_i_i_i_0210_i_4_reg_1158");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, k_buf_0_val_3_address0, "k_buf_0_val_3_address0");
    sc_trace(mVcdFile, k_buf_0_val_3_ce0, "k_buf_0_val_3_ce0");
    sc_trace(mVcdFile, k_buf_0_val_3_q0, "k_buf_0_val_3_q0");
    sc_trace(mVcdFile, k_buf_0_val_3_address1, "k_buf_0_val_3_address1");
    sc_trace(mVcdFile, k_buf_0_val_3_ce1, "k_buf_0_val_3_ce1");
    sc_trace(mVcdFile, k_buf_0_val_3_we1, "k_buf_0_val_3_we1");
    sc_trace(mVcdFile, k_buf_0_val_4_address0, "k_buf_0_val_4_address0");
    sc_trace(mVcdFile, k_buf_0_val_4_ce0, "k_buf_0_val_4_ce0");
    sc_trace(mVcdFile, k_buf_0_val_4_q0, "k_buf_0_val_4_q0");
    sc_trace(mVcdFile, k_buf_0_val_4_address1, "k_buf_0_val_4_address1");
    sc_trace(mVcdFile, k_buf_0_val_4_ce1, "k_buf_0_val_4_ce1");
    sc_trace(mVcdFile, k_buf_0_val_4_we1, "k_buf_0_val_4_we1");
    sc_trace(mVcdFile, k_buf_0_val_4_d1, "k_buf_0_val_4_d1");
    sc_trace(mVcdFile, k_buf_0_val_5_address0, "k_buf_0_val_5_address0");
    sc_trace(mVcdFile, k_buf_0_val_5_ce0, "k_buf_0_val_5_ce0");
    sc_trace(mVcdFile, k_buf_0_val_5_q0, "k_buf_0_val_5_q0");
    sc_trace(mVcdFile, k_buf_0_val_5_address1, "k_buf_0_val_5_address1");
    sc_trace(mVcdFile, k_buf_0_val_5_ce1, "k_buf_0_val_5_ce1");
    sc_trace(mVcdFile, k_buf_0_val_5_we1, "k_buf_0_val_5_we1");
    sc_trace(mVcdFile, k_buf_0_val_5_d1, "k_buf_0_val_5_d1");
    sc_trace(mVcdFile, t_V_reg_258, "t_V_reg_258");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_29_fu_639_p1, "tmp_29_fu_639_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, src_kernel_win_0_va_fu_132, "src_kernel_win_0_va_fu_132");
    sc_trace(mVcdFile, src_kernel_win_0_va_1_fu_136, "src_kernel_win_0_va_1_fu_136");
    sc_trace(mVcdFile, src_kernel_win_0_va_2_fu_140, "src_kernel_win_0_va_2_fu_140");
    sc_trace(mVcdFile, src_kernel_win_0_va_7_fu_762_p3, "src_kernel_win_0_va_7_fu_762_p3");
    sc_trace(mVcdFile, src_kernel_win_0_va_3_fu_144, "src_kernel_win_0_va_3_fu_144");
    sc_trace(mVcdFile, src_kernel_win_0_va_4_fu_148, "src_kernel_win_0_va_4_fu_148");
    sc_trace(mVcdFile, src_kernel_win_0_va_8_fu_780_p3, "src_kernel_win_0_va_8_fu_780_p3");
    sc_trace(mVcdFile, src_kernel_win_0_va_5_fu_152, "src_kernel_win_0_va_5_fu_152");
    sc_trace(mVcdFile, right_border_buf_0_s_fu_156, "right_border_buf_0_s_fu_156");
    sc_trace(mVcdFile, col_buf_0_val_0_0_fu_675_p3, "col_buf_0_val_0_0_fu_675_p3");
    sc_trace(mVcdFile, right_border_buf_0_1_fu_160, "right_border_buf_0_1_fu_160");
    sc_trace(mVcdFile, col_buf_0_val_2_0_fu_711_p3, "col_buf_0_val_2_0_fu_711_p3");
    sc_trace(mVcdFile, right_border_buf_0_2_fu_164, "right_border_buf_0_2_fu_164");
    sc_trace(mVcdFile, col_buf_0_val_1_0_fu_693_p3, "col_buf_0_val_1_0_fu_693_p3");
    sc_trace(mVcdFile, tmp_fu_326_p4, "tmp_fu_326_p4");
    sc_trace(mVcdFile, tmp_25_fu_359_p2, "tmp_25_fu_359_p2");
    sc_trace(mVcdFile, tmp_44_fu_365_p3, "tmp_44_fu_365_p3");
    sc_trace(mVcdFile, tmp_26_fu_379_p2, "tmp_26_fu_379_p2");
    sc_trace(mVcdFile, rev_fu_373_p2, "rev_fu_373_p2");
    sc_trace(mVcdFile, tmp_45_fu_390_p3, "tmp_45_fu_390_p3");
    sc_trace(mVcdFile, p_assign_4_1_fu_405_p2, "p_assign_4_1_fu_405_p2");
    sc_trace(mVcdFile, tmp_46_fu_411_p3, "tmp_46_fu_411_p3");
    sc_trace(mVcdFile, tmp_194_1_fu_425_p2, "tmp_194_1_fu_425_p2");
    sc_trace(mVcdFile, rev1_fu_419_p2, "rev1_fu_419_p2");
    sc_trace(mVcdFile, tmp_47_fu_436_p3, "tmp_47_fu_436_p3");
    sc_trace(mVcdFile, p_assign_4_2_fu_451_p2, "p_assign_4_2_fu_451_p2");
    sc_trace(mVcdFile, tmp_48_fu_457_p3, "tmp_48_fu_457_p3");
    sc_trace(mVcdFile, tmp_194_2_fu_471_p2, "tmp_194_2_fu_471_p2");
    sc_trace(mVcdFile, rev2_fu_465_p2, "rev2_fu_465_p2");
    sc_trace(mVcdFile, tmp_49_fu_482_p3, "tmp_49_fu_482_p3");
    sc_trace(mVcdFile, or_cond_i495_i_i_fu_384_p2, "or_cond_i495_i_i_fu_384_p2");
    sc_trace(mVcdFile, p_assign_5_fu_398_p3, "p_assign_5_fu_398_p3");
    sc_trace(mVcdFile, y_fu_497_p3, "y_fu_497_p3");
    sc_trace(mVcdFile, row_assign_7_fu_505_p2, "row_assign_7_fu_505_p2");
    sc_trace(mVcdFile, or_cond_i495_i_i_1_fu_430_p2, "or_cond_i495_i_i_1_fu_430_p2");
    sc_trace(mVcdFile, p_assign_5_1_fu_444_p3, "p_assign_5_1_fu_444_p3");
    sc_trace(mVcdFile, y_1_fu_514_p3, "y_1_fu_514_p3");
    sc_trace(mVcdFile, row_assign_7_1_fu_522_p2, "row_assign_7_1_fu_522_p2");
    sc_trace(mVcdFile, or_cond_i495_i_i_2_fu_476_p2, "or_cond_i495_i_i_2_fu_476_p2");
    sc_trace(mVcdFile, p_assign_5_2_fu_490_p3, "p_assign_5_2_fu_490_p3");
    sc_trace(mVcdFile, y_2_fu_531_p3, "y_2_fu_531_p3");
    sc_trace(mVcdFile, row_assign_7_2_fu_539_p2, "row_assign_7_2_fu_539_p2");
    sc_trace(mVcdFile, tmp_53_fu_559_p4, "tmp_53_fu_559_p4");
    sc_trace(mVcdFile, ImagLoc_x_fu_575_p2, "ImagLoc_x_fu_575_p2");
    sc_trace(mVcdFile, tmp_54_fu_581_p3, "tmp_54_fu_581_p3");
    sc_trace(mVcdFile, tmp_28_fu_595_p2, "tmp_28_fu_595_p2");
    sc_trace(mVcdFile, rev3_fu_589_p2, "rev3_fu_589_p2");
    sc_trace(mVcdFile, tmp_55_fu_606_p3, "tmp_55_fu_606_p3");
    sc_trace(mVcdFile, p_assign_1_fu_614_p3, "p_assign_1_fu_614_p3");
    sc_trace(mVcdFile, x_fu_621_p3, "x_fu_621_p3");
    sc_trace(mVcdFile, col_assign_1_fu_629_p2, "col_assign_1_fu_629_p2");
    sc_trace(mVcdFile, icmp2_fu_569_p2, "icmp2_fu_569_p2");
    sc_trace(mVcdFile, tmp_30_fu_664_p5, "tmp_30_fu_664_p5");
    sc_trace(mVcdFile, tmp_31_fu_682_p5, "tmp_31_fu_682_p5");
    sc_trace(mVcdFile, tmp_32_fu_700_p5, "tmp_32_fu_700_p5");
    sc_trace(mVcdFile, tmp_33_fu_733_p5, "tmp_33_fu_733_p5");
    sc_trace(mVcdFile, tmp_34_fu_751_p5, "tmp_34_fu_751_p5");
    sc_trace(mVcdFile, tmp_35_fu_769_p5, "tmp_35_fu_769_p5");
    sc_trace(mVcdFile, tmp_213_0_1_fu_799_p2, "tmp_213_0_1_fu_799_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_fu_805_p3, "temp_0_i_i_i_0210_i_fu_805_p3");
    sc_trace(mVcdFile, tmp_213_0_2_fu_813_p2, "tmp_213_0_2_fu_813_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_1_fu_819_p3, "temp_0_i_i_i_0210_i_1_fu_819_p3");
    sc_trace(mVcdFile, tmp_213_1_fu_827_p2, "tmp_213_1_fu_827_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_2_fu_833_p3, "temp_0_i_i_i_0210_i_2_fu_833_p3");
    sc_trace(mVcdFile, tmp_213_1_1_fu_841_p2, "tmp_213_1_1_fu_841_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_3_fu_847_p3, "temp_0_i_i_i_0210_i_3_fu_847_p3");
    sc_trace(mVcdFile, tmp_213_1_2_fu_855_p2, "tmp_213_1_2_fu_855_p2");
    sc_trace(mVcdFile, tmp_213_2_fu_901_p2, "tmp_213_2_fu_901_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_5_fu_906_p3, "temp_0_i_i_i_0210_i_5_fu_906_p3");
    sc_trace(mVcdFile, tmp_213_2_1_fu_913_p2, "tmp_213_2_1_fu_913_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_6_fu_919_p3, "temp_0_i_i_i_0210_i_6_fu_919_p3");
    sc_trace(mVcdFile, tmp_213_2_2_fu_927_p2, "tmp_213_2_2_fu_927_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0, "ap_block_pp0");
    sc_trace(mVcdFile, ap_enable_operation_99, "ap_enable_operation_99");
    sc_trace(mVcdFile, ap_enable_state3_pp0_iter0_stage0, "ap_enable_state3_pp0_iter0_stage0");
    sc_trace(mVcdFile, ap_enable_operation_116, "ap_enable_operation_116");
    sc_trace(mVcdFile, ap_enable_state4_pp0_iter1_stage0, "ap_enable_state4_pp0_iter1_stage0");
    sc_trace(mVcdFile, ap_predicate_op129_store_state4, "ap_predicate_op129_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_129, "ap_enable_operation_129");
    sc_trace(mVcdFile, ap_predicate_op134_store_state4, "ap_predicate_op134_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_134, "ap_enable_operation_134");
    sc_trace(mVcdFile, ap_enable_operation_102, "ap_enable_operation_102");
    sc_trace(mVcdFile, ap_enable_operation_119, "ap_enable_operation_119");
    sc_trace(mVcdFile, ap_predicate_op127_store_state4, "ap_predicate_op127_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_127, "ap_enable_operation_127");
    sc_trace(mVcdFile, ap_predicate_op132_store_state4, "ap_predicate_op132_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_132, "ap_enable_operation_132");
    sc_trace(mVcdFile, ap_enable_operation_104, "ap_enable_operation_104");
    sc_trace(mVcdFile, ap_enable_operation_122, "ap_enable_operation_122");
    sc_trace(mVcdFile, ap_predicate_op126_store_state4, "ap_predicate_op126_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_126, "ap_enable_operation_126");
    sc_trace(mVcdFile, ap_predicate_op131_store_state4, "ap_predicate_op131_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_131, "ap_enable_operation_131");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_734, "ap_condition_734");
#endif

    }
}

Dilate::~Dilate() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete k_buf_0_val_3_U;
    delete k_buf_0_val_4_U;
    delete k_buf_0_val_5_U;
    delete hls_fast_corner_mpcA_U48;
    delete hls_fast_corner_mpcA_U49;
    delete hls_fast_corner_mpcA_U50;
    delete hls_fast_corner_mpcA_U51;
    delete hls_fast_corner_mpcA_U52;
    delete hls_fast_corner_mpcA_U53;
}

void Dilate::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv8_0;
}

void Dilate::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, exitcond461_i_i_fu_304_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond461_i_i_fu_304_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond461_i_i_fu_304_p2.read()))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_548_p2.read()))) {
        t_V_5_reg_269 = j_V_fu_553_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond461_i_i_fu_304_p2.read()))) {
        t_V_5_reg_269 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        t_V_reg_258 = i_V_reg_1053.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        t_V_reg_258 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_548_p2.read()))) {
        brmerge_reg_1115 = brmerge_fu_634_p2.read();
        k_buf_0_val_3_addr_reg_1122 =  (sc_lv<11>) (tmp_29_fu_639_p1.read());
        k_buf_0_val_4_addr_reg_1135 =  (sc_lv<11>) (tmp_29_fu_639_p1.read());
        k_buf_0_val_5_addr_reg_1141 =  (sc_lv<11>) (tmp_29_fu_639_p1.read());
        or_cond_i_i_i_reg_1111 = or_cond_i_i_i_fu_600_p2.read();
        or_cond_i_i_reg_1147 = or_cond_i_i_fu_650_p2.read();
        tmp_56_reg_1128 = tmp_56_fu_646_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond460_i_i_reg_1102 = exitcond460_i_i_fu_548_p2.read();
        exitcond460_i_i_reg_1102_pp0_iter1_reg = exitcond460_i_i_reg_1102.read();
        or_cond_i_i_reg_1147_pp0_iter1_reg = or_cond_i_i_reg_1147.read();
        src_kernel_win_0_va_6_reg_1151 = src_kernel_win_0_va_6_fu_744_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_V_reg_1053 = i_V_fu_309_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond461_i_i_fu_304_p2.read()))) {
        icmp_reg_1067 = icmp_fu_336_p2.read();
        tmp_137_not_reg_1062 = tmp_137_not_fu_320_p2.read();
        tmp_167_2_reg_1076 = tmp_167_2_fu_348_p2.read();
        tmp_21_reg_1058 = tmp_21_fu_315_p2.read();
        tmp_23_reg_1072 = tmp_23_fu_342_p2.read();
        tmp_24_reg_1080 = tmp_24_fu_354_p2.read();
        tmp_50_reg_1087 = tmp_50_fu_510_p1.read();
        tmp_51_reg_1092 = tmp_51_fu_527_p1.read();
        tmp_52_reg_1097 = tmp_52_fu_544_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        right_border_buf_0_1_fu_160 = col_buf_0_val_2_0_fu_711_p3.read();
        right_border_buf_0_2_fu_164 = col_buf_0_val_1_0_fu_693_p3.read();
        right_border_buf_0_s_fu_156 = col_buf_0_val_0_0_fu_675_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_reg_1102_pp0_iter1_reg.read()))) {
        src_kernel_win_0_va_1_fu_136 = src_kernel_win_0_va_fu_132.read();
        src_kernel_win_0_va_fu_132 = src_kernel_win_0_va_6_reg_1151.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_reg_1102.read()))) {
        src_kernel_win_0_va_2_fu_140 = src_kernel_win_0_va_7_fu_762_p3.read();
        src_kernel_win_0_va_3_fu_144 = src_kernel_win_0_va_2_fu_140.read();
        src_kernel_win_0_va_4_fu_148 = src_kernel_win_0_va_8_fu_780_p3.read();
        src_kernel_win_0_va_5_fu_152 = src_kernel_win_0_va_4_fu_148.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_1147.read()))) {
        temp_0_i_i_i_0210_i_4_reg_1158 = temp_0_i_i_i_0210_i_4_fu_861_p3.read();
    }
}

void Dilate::thread_ImagLoc_x_fu_575_p2() {
    ImagLoc_x_fu_575_p2 = (!ap_const_lv32_FFFFFFFF.is_01() || !t_V_5_reg_269.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFF) + sc_biguint<32>(t_V_5_reg_269.read()));
}

void Dilate::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void Dilate::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Dilate::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Dilate::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void Dilate::thread_ap_block_pp0() {
    ap_block_pp0 = (esl_seteq<1,4,4>(ap_ST_fsm_pp0_stage0, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_pp0_stage0_subdone.read()));
}

void Dilate::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op125_read_state4.read())) || 
   (esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op133_read_state4.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_1147_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void Dilate::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op125_read_state4.read())) || 
   (esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op133_read_state4.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_1147_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void Dilate::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op125_read_state4.read())) || 
   (esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op133_read_state4.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_1147_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void Dilate::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Dilate::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op125_read_state4.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op133_read_state4.read())));
}

void Dilate::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = (esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_1147_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read()));
}

void Dilate::thread_ap_condition_734() {
    ap_condition_734 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1));
}

void Dilate::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond460_i_i_fu_548_p2.read())) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void Dilate::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond461_i_i_fu_304_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Dilate::thread_ap_enable_operation_102() {
    ap_enable_operation_102 = esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_548_p2.read());
}

void Dilate::thread_ap_enable_operation_104() {
    ap_enable_operation_104 = esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_548_p2.read());
}

void Dilate::thread_ap_enable_operation_116() {
    ap_enable_operation_116 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_enable_operation_119() {
    ap_enable_operation_119 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_enable_operation_122() {
    ap_enable_operation_122 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_enable_operation_126() {
    ap_enable_operation_126 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op126_store_state4.read());
}

void Dilate::thread_ap_enable_operation_127() {
    ap_enable_operation_127 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op127_store_state4.read());
}

void Dilate::thread_ap_enable_operation_129() {
    ap_enable_operation_129 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op129_store_state4.read());
}

void Dilate::thread_ap_enable_operation_131() {
    ap_enable_operation_131 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op131_store_state4.read());
}

void Dilate::thread_ap_enable_operation_132() {
    ap_enable_operation_132 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op132_store_state4.read());
}

void Dilate::thread_ap_enable_operation_134() {
    ap_enable_operation_134 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op134_store_state4.read());
}

void Dilate::thread_ap_enable_operation_99() {
    ap_enable_operation_99 = esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_548_p2.read());
}

void Dilate::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Dilate::thread_ap_enable_state3_pp0_iter0_stage0() {
    ap_enable_state3_pp0_iter0_stage0 = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_logic_1));
}

void Dilate::thread_ap_enable_state4_pp0_iter1_stage0() {
    ap_enable_state4_pp0_iter1_stage0 = (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1));
}

void Dilate::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Dilate::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Dilate::thread_ap_predicate_op125_read_state4() {
    ap_predicate_op125_read_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0));
}

void Dilate::thread_ap_predicate_op126_store_state4() {
    ap_predicate_op126_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_reg_1072.read()));
}

void Dilate::thread_ap_predicate_op127_store_state4() {
    ap_predicate_op127_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_reg_1072.read()));
}

void Dilate::thread_ap_predicate_op129_store_state4() {
    ap_predicate_op129_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_167_2_reg_1076.read()));
}

void Dilate::thread_ap_predicate_op131_store_state4() {
    ap_predicate_op131_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()));
}

void Dilate::thread_ap_predicate_op132_store_state4() {
    ap_predicate_op132_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()));
}

void Dilate::thread_ap_predicate_op133_read_state4() {
    ap_predicate_op133_read_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()));
}

void Dilate::thread_ap_predicate_op134_store_state4() {
    ap_predicate_op134_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()));
}

void Dilate::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond461_i_i_fu_304_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Dilate::thread_brmerge_fu_634_p2() {
    brmerge_fu_634_p2 = (tmp_28_fu_595_p2.read() | tmp_137_not_reg_1062.read());
}

void Dilate::thread_col_assign_1_fu_629_p2() {
    col_assign_1_fu_629_p2 = (!tmp_19_fu_292_p2.read().is_01() || !x_fu_621_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_19_fu_292_p2.read()) - sc_biguint<32>(x_fu_621_p3.read()));
}

void Dilate::thread_col_buf_0_val_0_0_fu_675_p3() {
    col_buf_0_val_0_0_fu_675_p3 = (!brmerge_reg_1115.read()[0].is_01())? sc_lv<8>(): ((brmerge_reg_1115.read()[0].to_bool())? k_buf_0_val_3_q0.read(): tmp_30_fu_664_p5.read());
}

void Dilate::thread_col_buf_0_val_1_0_fu_693_p3() {
    col_buf_0_val_1_0_fu_693_p3 = (!brmerge_reg_1115.read()[0].is_01())? sc_lv<8>(): ((brmerge_reg_1115.read()[0].to_bool())? k_buf_0_val_4_q0.read(): tmp_31_fu_682_p5.read());
}

void Dilate::thread_col_buf_0_val_2_0_fu_711_p3() {
    col_buf_0_val_2_0_fu_711_p3 = (!brmerge_reg_1115.read()[0].is_01())? sc_lv<8>(): ((brmerge_reg_1115.read()[0].to_bool())? k_buf_0_val_5_q0.read(): tmp_32_fu_700_p5.read());
}

void Dilate::thread_exitcond460_i_i_fu_548_p2() {
    exitcond460_i_i_fu_548_p2 = (!t_V_5_reg_269.read().is_01() || !tmp_s_fu_280_p2.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_5_reg_269.read() == tmp_s_fu_280_p2.read());
}

void Dilate::thread_exitcond461_i_i_fu_304_p2() {
    exitcond461_i_i_fu_304_p2 = (!t_V_reg_258.read().is_01() || !tmp_18_fu_286_p2.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_258.read() == tmp_18_fu_286_p2.read());
}

void Dilate::thread_i_V_fu_309_p2() {
    i_V_fu_309_p2 = (!t_V_reg_258.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_reg_258.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void Dilate::thread_icmp2_fu_569_p2() {
    icmp2_fu_569_p2 = (!tmp_53_fu_559_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_53_fu_559_p4.read() != ap_const_lv31_0);
}

void Dilate::thread_icmp_fu_336_p2() {
    icmp_fu_336_p2 = (!tmp_fu_326_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_326_p4.read() != ap_const_lv31_0);
}

void Dilate::thread_j_V_fu_553_p2() {
    j_V_fu_553_p2 = (!t_V_5_reg_269.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_5_reg_269.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void Dilate::thread_k_buf_0_val_3_address0() {
    k_buf_0_val_3_address0 =  (sc_lv<11>) (tmp_29_fu_639_p1.read());
}

void Dilate::thread_k_buf_0_val_3_address1() {
    k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_1122.read();
}

void Dilate::thread_k_buf_0_val_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        k_buf_0_val_3_ce0 = ap_const_logic_1;
    } else {
        k_buf_0_val_3_ce0 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_3_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_167_2_reg_1076.read())))) {
        k_buf_0_val_3_ce1 = ap_const_logic_1;
    } else {
        k_buf_0_val_3_ce1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_3_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_167_2_reg_1076.read())))) {
        k_buf_0_val_3_we1 = ap_const_logic_1;
    } else {
        k_buf_0_val_3_we1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_4_address0() {
    k_buf_0_val_4_address0 =  (sc_lv<11>) (tmp_29_fu_639_p1.read());
}

void Dilate::thread_k_buf_0_val_4_address1() {
    k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_1135.read();
}

void Dilate::thread_k_buf_0_val_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        k_buf_0_val_4_ce0 = ap_const_logic_1;
    } else {
        k_buf_0_val_4_ce0 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_4_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_reg_1072.read())))) {
        k_buf_0_val_4_ce1 = ap_const_logic_1;
    } else {
        k_buf_0_val_4_ce1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_4_d1() {
    if (esl_seteq<1,1,1>(ap_condition_734.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()))) {
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0.read();
        } else if ((esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_reg_1072.read()))) {
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout.read();
        } else {
            k_buf_0_val_4_d1 = "XXXXXXXX";
        }
    } else {
        k_buf_0_val_4_d1 = "XXXXXXXX";
    }
}

void Dilate::thread_k_buf_0_val_4_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_reg_1072.read())))) {
        k_buf_0_val_4_we1 = ap_const_logic_1;
    } else {
        k_buf_0_val_4_we1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_5_address0() {
    k_buf_0_val_5_address0 =  (sc_lv<11>) (tmp_29_fu_639_p1.read());
}

void Dilate::thread_k_buf_0_val_5_address1() {
    k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_1141.read();
}

void Dilate::thread_k_buf_0_val_5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        k_buf_0_val_5_ce0 = ap_const_logic_1;
    } else {
        k_buf_0_val_5_ce0 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_5_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_reg_1072.read())))) {
        k_buf_0_val_5_ce1 = ap_const_logic_1;
    } else {
        k_buf_0_val_5_ce1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_5_d1() {
    if (esl_seteq<1,1,1>(ap_condition_734.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()))) {
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0.read();
        } else if ((esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_reg_1072.read()))) {
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout.read();
        } else {
            k_buf_0_val_5_d1 = "XXXXXXXX";
        }
    } else {
        k_buf_0_val_5_d1 = "XXXXXXXX";
    }
}

void Dilate::thread_k_buf_0_val_5_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_reg_1072.read())))) {
        k_buf_0_val_5_we1 = ap_const_logic_1;
    } else {
        k_buf_0_val_5_we1 = ap_const_logic_0;
    }
}

void Dilate::thread_or_cond_i495_i_i_1_fu_430_p2() {
    or_cond_i495_i_i_1_fu_430_p2 = (tmp_194_1_fu_425_p2.read() & rev1_fu_419_p2.read());
}

void Dilate::thread_or_cond_i495_i_i_2_fu_476_p2() {
    or_cond_i495_i_i_2_fu_476_p2 = (tmp_194_2_fu_471_p2.read() & rev2_fu_465_p2.read());
}

void Dilate::thread_or_cond_i495_i_i_fu_384_p2() {
    or_cond_i495_i_i_fu_384_p2 = (tmp_26_fu_379_p2.read() & rev_fu_373_p2.read());
}

void Dilate::thread_or_cond_i_i_fu_650_p2() {
    or_cond_i_i_fu_650_p2 = (icmp_reg_1067.read() & icmp2_fu_569_p2.read());
}

void Dilate::thread_or_cond_i_i_i_fu_600_p2() {
    or_cond_i_i_i_fu_600_p2 = (tmp_28_fu_595_p2.read() & rev3_fu_589_p2.read());
}

void Dilate::thread_p_assign_1_fu_614_p3() {
    p_assign_1_fu_614_p3 = (!tmp_55_fu_606_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_55_fu_606_p3.read()[0].to_bool())? ap_const_lv32_0: tmp_19_fu_292_p2.read());
}

void Dilate::thread_p_assign_4_1_fu_405_p2() {
    p_assign_4_1_fu_405_p2 = (!ap_const_lv32_FFFFFFFE.is_01() || !t_V_reg_258.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFE) + sc_biguint<32>(t_V_reg_258.read()));
}

void Dilate::thread_p_assign_4_2_fu_451_p2() {
    p_assign_4_2_fu_451_p2 = (!ap_const_lv32_FFFFFFFD.is_01() || !t_V_reg_258.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFD) + sc_biguint<32>(t_V_reg_258.read()));
}

void Dilate::thread_p_assign_5_1_fu_444_p3() {
    p_assign_5_1_fu_444_p3 = (!tmp_47_fu_436_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_47_fu_436_p3.read()[0].to_bool())? ap_const_lv32_0: p_neg465_i_i_fu_298_p2.read());
}

void Dilate::thread_p_assign_5_2_fu_490_p3() {
    p_assign_5_2_fu_490_p3 = (!tmp_49_fu_482_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_49_fu_482_p3.read()[0].to_bool())? ap_const_lv32_0: p_neg465_i_i_fu_298_p2.read());
}

void Dilate::thread_p_assign_5_fu_398_p3() {
    p_assign_5_fu_398_p3 = (!tmp_45_fu_390_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_45_fu_390_p3.read()[0].to_bool())? ap_const_lv32_0: p_neg465_i_i_fu_298_p2.read());
}

void Dilate::thread_p_dst_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_1147_pp0_iter1_reg.read()))) {
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n.read();
    } else {
        p_dst_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void Dilate::thread_p_dst_data_stream_V_din() {
    p_dst_data_stream_V_din = (!tmp_213_2_2_fu_927_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_213_2_2_fu_927_p2.read()[0].to_bool())? src_kernel_win_0_va_6_reg_1151.read(): temp_0_i_i_i_0210_i_6_fu_919_p3.read());
}

void Dilate::thread_p_dst_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_1147_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_dst_data_stream_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_V_write = ap_const_logic_0;
    }
}

void Dilate::thread_p_neg465_i_i_fu_298_p2() {
    p_neg465_i_i_fu_298_p2 = (!p_src_rows_V.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(p_src_rows_V.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void Dilate::thread_p_src_data_stream_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_1067.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_1111.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_1067.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_21_reg_1058.read())))) {
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n.read();
    } else {
        p_src_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void Dilate::thread_p_src_data_stream_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op125_read_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op133_read_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
        p_src_data_stream_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_V_read = ap_const_logic_0;
    }
}

void Dilate::thread_rev1_fu_419_p2() {
    rev1_fu_419_p2 = (tmp_46_fu_411_p3.read() ^ ap_const_lv1_1);
}

void Dilate::thread_rev2_fu_465_p2() {
    rev2_fu_465_p2 = (tmp_48_fu_457_p3.read() ^ ap_const_lv1_1);
}

void Dilate::thread_rev3_fu_589_p2() {
    rev3_fu_589_p2 = (tmp_54_fu_581_p3.read() ^ ap_const_lv1_1);
}

void Dilate::thread_rev_fu_373_p2() {
    rev_fu_373_p2 = (tmp_44_fu_365_p3.read() ^ ap_const_lv1_1);
}

void Dilate::thread_row_assign_7_1_fu_522_p2() {
    row_assign_7_1_fu_522_p2 = (!p_neg465_i_i_fu_298_p2.read().is_01() || !y_1_fu_514_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_neg465_i_i_fu_298_p2.read()) - sc_biguint<32>(y_1_fu_514_p3.read()));
}

void Dilate::thread_row_assign_7_2_fu_539_p2() {
    row_assign_7_2_fu_539_p2 = (!p_neg465_i_i_fu_298_p2.read().is_01() || !y_2_fu_531_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_neg465_i_i_fu_298_p2.read()) - sc_biguint<32>(y_2_fu_531_p3.read()));
}

void Dilate::thread_row_assign_7_fu_505_p2() {
    row_assign_7_fu_505_p2 = (!p_neg465_i_i_fu_298_p2.read().is_01() || !y_fu_497_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_neg465_i_i_fu_298_p2.read()) - sc_biguint<32>(y_fu_497_p3.read()));
}

void Dilate::thread_src_kernel_win_0_va_6_fu_744_p3() {
    src_kernel_win_0_va_6_fu_744_p3 = (!tmp_24_reg_1080.read()[0].is_01())? sc_lv<8>(): ((tmp_24_reg_1080.read()[0].to_bool())? tmp_33_fu_733_p5.read(): col_buf_0_val_0_0_fu_675_p3.read());
}

void Dilate::thread_src_kernel_win_0_va_7_fu_762_p3() {
    src_kernel_win_0_va_7_fu_762_p3 = (!tmp_24_reg_1080.read()[0].is_01())? sc_lv<8>(): ((tmp_24_reg_1080.read()[0].to_bool())? tmp_34_fu_751_p5.read(): col_buf_0_val_1_0_fu_693_p3.read());
}

void Dilate::thread_src_kernel_win_0_va_8_fu_780_p3() {
    src_kernel_win_0_va_8_fu_780_p3 = (!tmp_24_reg_1080.read()[0].is_01())? sc_lv<8>(): ((tmp_24_reg_1080.read()[0].to_bool())? tmp_35_fu_769_p5.read(): col_buf_0_val_2_0_fu_711_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_1_fu_819_p3() {
    temp_0_i_i_i_0210_i_1_fu_819_p3 = (!tmp_213_0_2_fu_813_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_213_0_2_fu_813_p2.read()[0].to_bool())? src_kernel_win_0_va_8_fu_780_p3.read(): temp_0_i_i_i_0210_i_fu_805_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_2_fu_833_p3() {
    temp_0_i_i_i_0210_i_2_fu_833_p3 = (!tmp_213_1_fu_827_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_213_1_fu_827_p2.read()[0].to_bool())? src_kernel_win_0_va_3_fu_144.read(): temp_0_i_i_i_0210_i_1_fu_819_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_3_fu_847_p3() {
    temp_0_i_i_i_0210_i_3_fu_847_p3 = (!tmp_213_1_1_fu_841_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_213_1_1_fu_841_p2.read()[0].to_bool())? src_kernel_win_0_va_2_fu_140.read(): temp_0_i_i_i_0210_i_2_fu_833_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_4_fu_861_p3() {
    temp_0_i_i_i_0210_i_4_fu_861_p3 = (!tmp_213_1_2_fu_855_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_213_1_2_fu_855_p2.read()[0].to_bool())? src_kernel_win_0_va_7_fu_762_p3.read(): temp_0_i_i_i_0210_i_3_fu_847_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_5_fu_906_p3() {
    temp_0_i_i_i_0210_i_5_fu_906_p3 = (!tmp_213_2_fu_901_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_213_2_fu_901_p2.read()[0].to_bool())? src_kernel_win_0_va_1_fu_136.read(): temp_0_i_i_i_0210_i_4_reg_1158.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_6_fu_919_p3() {
    temp_0_i_i_i_0210_i_6_fu_919_p3 = (!tmp_213_2_1_fu_913_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_213_2_1_fu_913_p2.read()[0].to_bool())? src_kernel_win_0_va_fu_132.read(): temp_0_i_i_i_0210_i_5_fu_906_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_fu_805_p3() {
    temp_0_i_i_i_0210_i_fu_805_p3 = (!tmp_213_0_1_fu_799_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_213_0_1_fu_799_p2.read()[0].to_bool())? src_kernel_win_0_va_4_fu_148.read(): src_kernel_win_0_va_5_fu_152.read());
}

void Dilate::thread_tmp_137_not_fu_320_p2() {
    tmp_137_not_fu_320_p2 = (tmp_21_fu_315_p2.read() ^ ap_const_lv1_1);
}

void Dilate::thread_tmp_167_2_fu_348_p2() {
    tmp_167_2_fu_348_p2 = (!t_V_reg_258.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_258.read() == ap_const_lv32_1);
}

void Dilate::thread_tmp_18_fu_286_p2() {
    tmp_18_fu_286_p2 = (!p_src_rows_V.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<32>(): (sc_biguint<32>(p_src_rows_V.read()) + sc_biguint<32>(ap_const_lv32_2));
}

void Dilate::thread_tmp_194_1_fu_425_p2() {
    tmp_194_1_fu_425_p2 = (!p_assign_4_1_fu_405_p2.read().is_01() || !p_src_rows_V.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p_assign_4_1_fu_405_p2.read()) < sc_bigint<32>(p_src_rows_V.read()));
}

void Dilate::thread_tmp_194_2_fu_471_p2() {
    tmp_194_2_fu_471_p2 = (!p_assign_4_2_fu_451_p2.read().is_01() || !p_src_rows_V.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p_assign_4_2_fu_451_p2.read()) < sc_bigint<32>(p_src_rows_V.read()));
}

void Dilate::thread_tmp_19_fu_292_p2() {
    tmp_19_fu_292_p2 = (!p_src_cols_V.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(p_src_cols_V.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void Dilate::thread_tmp_213_0_1_fu_799_p2() {
    tmp_213_0_1_fu_799_p2 = (!src_kernel_win_0_va_4_fu_148.read().is_01() || !src_kernel_win_0_va_5_fu_152.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_4_fu_148.read()) > sc_biguint<8>(src_kernel_win_0_va_5_fu_152.read()));
}

void Dilate::thread_tmp_213_0_2_fu_813_p2() {
    tmp_213_0_2_fu_813_p2 = (!src_kernel_win_0_va_8_fu_780_p3.read().is_01() || !temp_0_i_i_i_0210_i_fu_805_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_8_fu_780_p3.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_fu_805_p3.read()));
}

void Dilate::thread_tmp_213_1_1_fu_841_p2() {
    tmp_213_1_1_fu_841_p2 = (!src_kernel_win_0_va_2_fu_140.read().is_01() || !temp_0_i_i_i_0210_i_2_fu_833_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_2_fu_140.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_2_fu_833_p3.read()));
}

void Dilate::thread_tmp_213_1_2_fu_855_p2() {
    tmp_213_1_2_fu_855_p2 = (!src_kernel_win_0_va_7_fu_762_p3.read().is_01() || !temp_0_i_i_i_0210_i_3_fu_847_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_7_fu_762_p3.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_3_fu_847_p3.read()));
}

void Dilate::thread_tmp_213_1_fu_827_p2() {
    tmp_213_1_fu_827_p2 = (!src_kernel_win_0_va_3_fu_144.read().is_01() || !temp_0_i_i_i_0210_i_1_fu_819_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_3_fu_144.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_1_fu_819_p3.read()));
}

void Dilate::thread_tmp_213_2_1_fu_913_p2() {
    tmp_213_2_1_fu_913_p2 = (!src_kernel_win_0_va_fu_132.read().is_01() || !temp_0_i_i_i_0210_i_5_fu_906_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_fu_132.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_5_fu_906_p3.read()));
}

void Dilate::thread_tmp_213_2_2_fu_927_p2() {
    tmp_213_2_2_fu_927_p2 = (!src_kernel_win_0_va_6_reg_1151.read().is_01() || !temp_0_i_i_i_0210_i_6_fu_919_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_6_reg_1151.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_6_fu_919_p3.read()));
}

void Dilate::thread_tmp_213_2_fu_901_p2() {
    tmp_213_2_fu_901_p2 = (!src_kernel_win_0_va_1_fu_136.read().is_01() || !temp_0_i_i_i_0210_i_4_reg_1158.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_1_fu_136.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_4_reg_1158.read()));
}

void Dilate::thread_tmp_21_fu_315_p2() {
    tmp_21_fu_315_p2 = (!t_V_reg_258.read().is_01() || !p_src_rows_V.read().is_01())? sc_lv<1>(): (sc_biguint<32>(t_V_reg_258.read()) < sc_biguint<32>(p_src_rows_V.read()));
}

void Dilate::thread_tmp_23_fu_342_p2() {
    tmp_23_fu_342_p2 = (!t_V_reg_258.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_258.read() == ap_const_lv32_0);
}

void Dilate::thread_tmp_24_fu_354_p2() {
    tmp_24_fu_354_p2 = (!t_V_reg_258.read().is_01() || !p_src_rows_V.read().is_01())? sc_lv<1>(): (sc_biguint<32>(t_V_reg_258.read()) > sc_biguint<32>(p_src_rows_V.read()));
}

void Dilate::thread_tmp_25_fu_359_p2() {
    tmp_25_fu_359_p2 = (!ap_const_lv32_FFFFFFFF.is_01() || !t_V_reg_258.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFF) + sc_biguint<32>(t_V_reg_258.read()));
}

void Dilate::thread_tmp_26_fu_379_p2() {
    tmp_26_fu_379_p2 = (!tmp_25_fu_359_p2.read().is_01() || !p_src_rows_V.read().is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_25_fu_359_p2.read()) < sc_bigint<32>(p_src_rows_V.read()));
}

void Dilate::thread_tmp_28_fu_595_p2() {
    tmp_28_fu_595_p2 = (!ImagLoc_x_fu_575_p2.read().is_01() || !p_src_cols_V.read().is_01())? sc_lv<1>(): (sc_bigint<32>(ImagLoc_x_fu_575_p2.read()) < sc_bigint<32>(p_src_cols_V.read()));
}

void Dilate::thread_tmp_29_fu_639_p1() {
    tmp_29_fu_639_p1 = esl_zext<64,32>(x_fu_621_p3.read());
}

void Dilate::thread_tmp_44_fu_365_p3() {
    tmp_44_fu_365_p3 = tmp_25_fu_359_p2.read().range(31, 31);
}

void Dilate::thread_tmp_45_fu_390_p3() {
    tmp_45_fu_390_p3 = tmp_25_fu_359_p2.read().range(31, 31);
}

void Dilate::thread_tmp_46_fu_411_p3() {
    tmp_46_fu_411_p3 = p_assign_4_1_fu_405_p2.read().range(31, 31);
}

void Dilate::thread_tmp_47_fu_436_p3() {
    tmp_47_fu_436_p3 = p_assign_4_1_fu_405_p2.read().range(31, 31);
}

void Dilate::thread_tmp_48_fu_457_p3() {
    tmp_48_fu_457_p3 = p_assign_4_2_fu_451_p2.read().range(31, 31);
}

void Dilate::thread_tmp_49_fu_482_p3() {
    tmp_49_fu_482_p3 = p_assign_4_2_fu_451_p2.read().range(31, 31);
}

void Dilate::thread_tmp_50_fu_510_p1() {
    tmp_50_fu_510_p1 = row_assign_7_fu_505_p2.read().range(2-1, 0);
}

void Dilate::thread_tmp_51_fu_527_p1() {
    tmp_51_fu_527_p1 = row_assign_7_1_fu_522_p2.read().range(2-1, 0);
}

void Dilate::thread_tmp_52_fu_544_p1() {
    tmp_52_fu_544_p1 = row_assign_7_2_fu_539_p2.read().range(2-1, 0);
}

void Dilate::thread_tmp_53_fu_559_p4() {
    tmp_53_fu_559_p4 = t_V_5_reg_269.read().range(31, 1);
}

void Dilate::thread_tmp_54_fu_581_p3() {
    tmp_54_fu_581_p3 = ImagLoc_x_fu_575_p2.read().range(31, 31);
}

void Dilate::thread_tmp_55_fu_606_p3() {
    tmp_55_fu_606_p3 = ImagLoc_x_fu_575_p2.read().range(31, 31);
}

void Dilate::thread_tmp_56_fu_646_p1() {
    tmp_56_fu_646_p1 = col_assign_1_fu_629_p2.read().range(2-1, 0);
}

void Dilate::thread_tmp_fu_326_p4() {
    tmp_fu_326_p4 = t_V_reg_258.read().range(31, 1);
}

void Dilate::thread_tmp_s_fu_280_p2() {
    tmp_s_fu_280_p2 = (!p_src_cols_V.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<32>(): (sc_biguint<32>(p_src_cols_V.read()) + sc_biguint<32>(ap_const_lv32_2));
}

void Dilate::thread_x_fu_621_p3() {
    x_fu_621_p3 = (!or_cond_i_i_i_fu_600_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond_i_i_i_fu_600_p2.read()[0].to_bool())? ImagLoc_x_fu_575_p2.read(): p_assign_1_fu_614_p3.read());
}

void Dilate::thread_y_1_fu_514_p3() {
    y_1_fu_514_p3 = (!or_cond_i495_i_i_1_fu_430_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond_i495_i_i_1_fu_430_p2.read()[0].to_bool())? p_assign_4_1_fu_405_p2.read(): p_assign_5_1_fu_444_p3.read());
}

void Dilate::thread_y_2_fu_531_p3() {
    y_2_fu_531_p3 = (!or_cond_i495_i_i_2_fu_476_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond_i495_i_i_2_fu_476_p2.read()[0].to_bool())? p_assign_4_2_fu_451_p2.read(): p_assign_5_2_fu_490_p3.read());
}

void Dilate::thread_y_fu_497_p3() {
    y_fu_497_p3 = (!or_cond_i495_i_i_fu_384_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond_i495_i_i_fu_384_p2.read()[0].to_bool())? tmp_25_fu_359_p2.read(): p_assign_5_fu_398_p3.read());
}

void Dilate::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond461_i_i_fu_304_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond460_i_i_fu_548_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, exitcond460_i_i_fu_548_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

