// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "AXIvideo2Mat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic AXIvideo2Mat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic AXIvideo2Mat::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state1 = "1";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state2 = "10";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state3 = "100";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state4 = "1000";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_pp1_stage0 = "10000";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state8 = "100000";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state9 = "1000000";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state10 = "10000000";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool AXIvideo2Mat::ap_const_boolean_1 = true;
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_1 = "1";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_4 = "100";
const bool AXIvideo2Mat::ap_const_boolean_0 = false;
const sc_lv<1> AXIvideo2Mat::ap_const_lv1_0 = "0";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_6 = "110";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_3 = "11";
const sc_lv<1> AXIvideo2Mat::ap_const_lv1_1 = "1";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_7 = "111";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_2 = "10";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_5 = "101";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_8 = "1000";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_F = "1111";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_10 = "10000";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_17 = "10111";

AXIvideo2Mat::AXIvideo2Mat(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXI_video_strm_V_data_V_blk_n);
    sensitive << ( AXI_video_strm_V_data_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_reg_512 );
    sensitive << ( brmerge_fu_438_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_AXI_video_strm_V_data_V_read);
    sensitive << ( AXI_video_strm_V_id_V0_update );

    SC_METHOD(thread_AXI_video_strm_V_dest_V_blk_n);
    sensitive << ( AXI_video_strm_V_dest_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_reg_512 );
    sensitive << ( brmerge_fu_438_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_AXI_video_strm_V_dest_V_read);
    sensitive << ( AXI_video_strm_V_id_V0_update );

    SC_METHOD(thread_AXI_video_strm_V_id_V0_status);
    sensitive << ( AXI_video_strm_V_data_V_empty_n );
    sensitive << ( AXI_video_strm_V_keep_V_empty_n );
    sensitive << ( AXI_video_strm_V_strb_V_empty_n );
    sensitive << ( AXI_video_strm_V_user_V_empty_n );
    sensitive << ( AXI_video_strm_V_last_V_empty_n );
    sensitive << ( AXI_video_strm_V_id_V_empty_n );
    sensitive << ( AXI_video_strm_V_dest_V_empty_n );

    SC_METHOD(thread_AXI_video_strm_V_id_V0_update);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( AXI_video_strm_V_id_V0_status );
    sensitive << ( ap_predicate_op59_read_state6 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_AXI_video_strm_V_id_V_blk_n);
    sensitive << ( AXI_video_strm_V_id_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_reg_512 );
    sensitive << ( brmerge_fu_438_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_AXI_video_strm_V_id_V_read);
    sensitive << ( AXI_video_strm_V_id_V0_update );

    SC_METHOD(thread_AXI_video_strm_V_keep_V_blk_n);
    sensitive << ( AXI_video_strm_V_keep_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_reg_512 );
    sensitive << ( brmerge_fu_438_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_AXI_video_strm_V_keep_V_read);
    sensitive << ( AXI_video_strm_V_id_V0_update );

    SC_METHOD(thread_AXI_video_strm_V_last_V_blk_n);
    sensitive << ( AXI_video_strm_V_last_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_reg_512 );
    sensitive << ( brmerge_fu_438_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_AXI_video_strm_V_last_V_read);
    sensitive << ( AXI_video_strm_V_id_V0_update );

    SC_METHOD(thread_AXI_video_strm_V_strb_V_blk_n);
    sensitive << ( AXI_video_strm_V_strb_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_reg_512 );
    sensitive << ( brmerge_fu_438_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_AXI_video_strm_V_strb_V_read);
    sensitive << ( AXI_video_strm_V_id_V0_update );

    SC_METHOD(thread_AXI_video_strm_V_user_V_blk_n);
    sensitive << ( AXI_video_strm_V_user_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_reg_512 );
    sensitive << ( brmerge_fu_438_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_AXI_video_strm_V_user_V_read);
    sensitive << ( AXI_video_strm_V_id_V0_update );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_01001);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( AXI_video_strm_V_id_V0_status );
    sensitive << ( ap_predicate_op59_read_state6 );

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( AXI_video_strm_V_id_V0_status );
    sensitive << ( ap_predicate_op59_read_state6 );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( AXI_video_strm_V_id_V0_status );
    sensitive << ( ap_predicate_op59_read_state6 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state5_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state6_pp1_stage0_iter1);
    sensitive << ( AXI_video_strm_V_id_V0_status );
    sensitive << ( ap_predicate_op59_read_state6 );

    SC_METHOD(thread_ap_block_state7_pp1_stage0_iter2);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );

    SC_METHOD(thread_ap_block_state9);
    sensitive << ( AXI_video_strm_V_id_V0_status );
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_ap_condition_249);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_ap_condition_287);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond_reg_512 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter1_state6);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond2_fu_413_p2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ap_phi_mux_axi_data_V_1_phi_fu_315_p4);
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( axi_data_V_1_reg_312 );
    sensitive << ( p_Val2_s_reg_348 );

    SC_METHOD(thread_ap_phi_mux_eol_1_phi_fu_304_p4);
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( eol_1_reg_301 );
    sensitive << ( axi_last_V_2_reg_335 );

    SC_METHOD(thread_ap_phi_mux_eol_2_phi_fu_387_p4);
    sensitive << ( eol_2_reg_384 );

    SC_METHOD(thread_ap_phi_mux_eol_phi_fu_327_p4);
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( eol_reg_323 );
    sensitive << ( axi_last_V_2_reg_335 );

    SC_METHOD(thread_ap_phi_mux_p_Val2_s_phi_fu_352_p4);
    sensitive << ( AXI_video_strm_V_data_V_dout );
    sensitive << ( brmerge_fu_438_p2 );
    sensitive << ( ap_phi_mux_axi_data_V_1_phi_fu_315_p4 );
    sensitive << ( ap_phi_reg_pp1_iter1_p_Val2_s_reg_348 );
    sensitive << ( ap_condition_287 );

    SC_METHOD(thread_ap_phi_reg_pp1_iter1_axi_last_V_2_reg_335);

    SC_METHOD(thread_ap_phi_reg_pp1_iter1_p_Val2_s_reg_348);

    SC_METHOD(thread_ap_predicate_op59_read_state6);
    sensitive << ( exitcond_reg_512 );
    sensitive << ( brmerge_fu_438_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond2_fu_413_p2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_brmerge_fu_438_p2);
    sensitive << ( ap_phi_mux_eol_phi_fu_327_p4 );
    sensitive << ( sof_1_fu_204 );

    SC_METHOD(thread_exitcond2_fu_413_p2);
    sensitive << ( img_rows_V_read );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( t_V_reg_279 );

    SC_METHOD(thread_exitcond_fu_424_p2);
    sensitive << ( img_cols_V_read );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( t_V_2_reg_290 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_i_V_fu_418_p2);
    sensitive << ( t_V_reg_279 );

    SC_METHOD(thread_img_data_stream_0_V_blk_n);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );

    SC_METHOD(thread_img_data_stream_0_V_din);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( tmp_8_reg_525 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_img_data_stream_0_V_write);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_img_data_stream_1_V_blk_n);
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );

    SC_METHOD(thread_img_data_stream_1_V_din);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( tmp_4_reg_530 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_img_data_stream_1_V_write);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_img_data_stream_2_V_blk_n);
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );

    SC_METHOD(thread_img_data_stream_2_V_din);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( tmp_5_reg_535 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_img_data_stream_2_V_write);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( exitcond_reg_512_pp1_iter1_reg );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_j_V_fu_429_p2);
    sensitive << ( t_V_2_reg_290 );

    SC_METHOD(thread_tmp_8_fu_444_p1);
    sensitive << ( ap_phi_mux_p_Val2_s_phi_fu_352_p4 );

    SC_METHOD(thread_tmp_user_V_fu_404_p1);
    sensitive << ( AXI_video_strm_V_user_V_dout );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_phi_mux_eol_2_phi_fu_387_p4 );
    sensitive << ( AXI_video_strm_V_id_V0_status );
    sensitive << ( exitcond2_fu_413_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( eol_2_reg_384 );
    sensitive << ( tmp_user_V_fu_404_p1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000001";
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "AXIvideo2Mat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_dout, "(port)AXI_video_strm_V_data_V_dout");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_empty_n, "(port)AXI_video_strm_V_data_V_empty_n");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_read, "(port)AXI_video_strm_V_data_V_read");
    sc_trace(mVcdFile, AXI_video_strm_V_keep_V_dout, "(port)AXI_video_strm_V_keep_V_dout");
    sc_trace(mVcdFile, AXI_video_strm_V_keep_V_empty_n, "(port)AXI_video_strm_V_keep_V_empty_n");
    sc_trace(mVcdFile, AXI_video_strm_V_keep_V_read, "(port)AXI_video_strm_V_keep_V_read");
    sc_trace(mVcdFile, AXI_video_strm_V_strb_V_dout, "(port)AXI_video_strm_V_strb_V_dout");
    sc_trace(mVcdFile, AXI_video_strm_V_strb_V_empty_n, "(port)AXI_video_strm_V_strb_V_empty_n");
    sc_trace(mVcdFile, AXI_video_strm_V_strb_V_read, "(port)AXI_video_strm_V_strb_V_read");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_dout, "(port)AXI_video_strm_V_user_V_dout");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_empty_n, "(port)AXI_video_strm_V_user_V_empty_n");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_read, "(port)AXI_video_strm_V_user_V_read");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_dout, "(port)AXI_video_strm_V_last_V_dout");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_empty_n, "(port)AXI_video_strm_V_last_V_empty_n");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_read, "(port)AXI_video_strm_V_last_V_read");
    sc_trace(mVcdFile, AXI_video_strm_V_id_V_dout, "(port)AXI_video_strm_V_id_V_dout");
    sc_trace(mVcdFile, AXI_video_strm_V_id_V_empty_n, "(port)AXI_video_strm_V_id_V_empty_n");
    sc_trace(mVcdFile, AXI_video_strm_V_id_V_read, "(port)AXI_video_strm_V_id_V_read");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_dout, "(port)AXI_video_strm_V_dest_V_dout");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_empty_n, "(port)AXI_video_strm_V_dest_V_empty_n");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_read, "(port)AXI_video_strm_V_dest_V_read");
    sc_trace(mVcdFile, img_rows_V_read, "(port)img_rows_V_read");
    sc_trace(mVcdFile, img_cols_V_read, "(port)img_cols_V_read");
    sc_trace(mVcdFile, img_data_stream_0_V_din, "(port)img_data_stream_0_V_din");
    sc_trace(mVcdFile, img_data_stream_0_V_full_n, "(port)img_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_data_stream_0_V_write, "(port)img_data_stream_0_V_write");
    sc_trace(mVcdFile, img_data_stream_1_V_din, "(port)img_data_stream_1_V_din");
    sc_trace(mVcdFile, img_data_stream_1_V_full_n, "(port)img_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_data_stream_1_V_write, "(port)img_data_stream_1_V_write");
    sc_trace(mVcdFile, img_data_stream_2_V_din, "(port)img_data_stream_2_V_din");
    sc_trace(mVcdFile, img_data_stream_2_V_full_n, "(port)img_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_data_stream_2_V_write, "(port)img_data_stream_2_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_blk_n, "AXI_video_strm_V_data_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, exitcond_reg_512, "exitcond_reg_512");
    sc_trace(mVcdFile, brmerge_fu_438_p2, "brmerge_fu_438_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_phi_mux_eol_2_phi_fu_387_p4, "ap_phi_mux_eol_2_phi_fu_387_p4");
    sc_trace(mVcdFile, AXI_video_strm_V_keep_V_blk_n, "AXI_video_strm_V_keep_V_blk_n");
    sc_trace(mVcdFile, AXI_video_strm_V_strb_V_blk_n, "AXI_video_strm_V_strb_V_blk_n");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_blk_n, "AXI_video_strm_V_user_V_blk_n");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_blk_n, "AXI_video_strm_V_last_V_blk_n");
    sc_trace(mVcdFile, AXI_video_strm_V_id_V_blk_n, "AXI_video_strm_V_id_V_blk_n");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_blk_n, "AXI_video_strm_V_dest_V_blk_n");
    sc_trace(mVcdFile, img_data_stream_0_V_blk_n, "img_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter2, "ap_enable_reg_pp1_iter2");
    sc_trace(mVcdFile, exitcond_reg_512_pp1_iter1_reg, "exitcond_reg_512_pp1_iter1_reg");
    sc_trace(mVcdFile, img_data_stream_1_V_blk_n, "img_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, img_data_stream_2_V_blk_n, "img_data_stream_2_V_blk_n");
    sc_trace(mVcdFile, t_V_2_reg_290, "t_V_2_reg_290");
    sc_trace(mVcdFile, eol_1_reg_301, "eol_1_reg_301");
    sc_trace(mVcdFile, axi_data_V_1_reg_312, "axi_data_V_1_reg_312");
    sc_trace(mVcdFile, eol_reg_323, "eol_reg_323");
    sc_trace(mVcdFile, axi_last_V_2_reg_335, "axi_last_V_2_reg_335");
    sc_trace(mVcdFile, p_Val2_s_reg_348, "p_Val2_s_reg_348");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, tmp_data_V_reg_483, "tmp_data_V_reg_483");
    sc_trace(mVcdFile, AXI_video_strm_V_id_V0_status, "AXI_video_strm_V_id_V0_status");
    sc_trace(mVcdFile, tmp_last_V_reg_491, "tmp_last_V_reg_491");
    sc_trace(mVcdFile, exitcond2_fu_413_p2, "exitcond2_fu_413_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_V_fu_418_p2, "i_V_fu_418_p2");
    sc_trace(mVcdFile, i_V_reg_507, "i_V_reg_507");
    sc_trace(mVcdFile, exitcond_fu_424_p2, "exitcond_fu_424_p2");
    sc_trace(mVcdFile, ap_block_state5_pp1_stage0_iter0, "ap_block_state5_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_predicate_op59_read_state6, "ap_predicate_op59_read_state6");
    sc_trace(mVcdFile, ap_block_state6_pp1_stage0_iter1, "ap_block_state6_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp1_stage0_iter2, "ap_block_state7_pp1_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, j_V_fu_429_p2, "j_V_fu_429_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, tmp_8_fu_444_p1, "tmp_8_fu_444_p1");
    sc_trace(mVcdFile, tmp_8_reg_525, "tmp_8_reg_525");
    sc_trace(mVcdFile, tmp_4_reg_530, "tmp_4_reg_530");
    sc_trace(mVcdFile, tmp_5_reg_535, "tmp_5_reg_535");
    sc_trace(mVcdFile, ap_block_state9, "ap_block_state9");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter1_state6, "ap_condition_pp1_exit_iter1_state6");
    sc_trace(mVcdFile, axi_last_V_3_reg_360, "axi_last_V_3_reg_360");
    sc_trace(mVcdFile, axi_last_V1_reg_259, "axi_last_V1_reg_259");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, axi_data_V_3_reg_372, "axi_data_V_3_reg_372");
    sc_trace(mVcdFile, axi_data_V1_reg_269, "axi_data_V1_reg_269");
    sc_trace(mVcdFile, t_V_reg_279, "t_V_reg_279");
    sc_trace(mVcdFile, ap_phi_mux_eol_1_phi_fu_304_p4, "ap_phi_mux_eol_1_phi_fu_304_p4");
    sc_trace(mVcdFile, ap_phi_mux_axi_data_V_1_phi_fu_315_p4, "ap_phi_mux_axi_data_V_1_phi_fu_315_p4");
    sc_trace(mVcdFile, ap_phi_mux_eol_phi_fu_327_p4, "ap_phi_mux_eol_phi_fu_327_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp1_iter1_axi_last_V_2_reg_335, "ap_phi_reg_pp1_iter1_axi_last_V_2_reg_335");
    sc_trace(mVcdFile, ap_phi_mux_p_Val2_s_phi_fu_352_p4, "ap_phi_mux_p_Val2_s_phi_fu_352_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp1_iter1_p_Val2_s_reg_348, "ap_phi_reg_pp1_iter1_p_Val2_s_reg_348");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, eol_2_reg_384, "eol_2_reg_384");
    sc_trace(mVcdFile, AXI_video_strm_V_id_V0_update, "AXI_video_strm_V_id_V0_update");
    sc_trace(mVcdFile, ap_block_pp1_stage0_01001, "ap_block_pp1_stage0_01001");
    sc_trace(mVcdFile, sof_1_fu_204, "sof_1_fu_204");
    sc_trace(mVcdFile, tmp_user_V_fu_404_p1, "tmp_user_V_fu_404_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, ap_condition_287, "ap_condition_287");
    sc_trace(mVcdFile, ap_condition_249, "ap_condition_249");
#endif

    }
}

AXIvideo2Mat::~AXIvideo2Mat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void AXIvideo2Mat::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(exitcond2_fu_413_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(exitcond_fu_424_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_413_p2.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_413_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter1_state6.read())))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter1_state6.read()))) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_413_p2.read()))) {
            ap_enable_reg_pp1_iter2 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        axi_data_V1_reg_269 = tmp_data_V_reg_483.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        axi_data_V1_reg_269 = axi_data_V_3_reg_372.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        axi_data_V_1_reg_312 = p_Val2_s_reg_348.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_413_p2.read()))) {
        axi_data_V_1_reg_312 = axi_data_V1_reg_269.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        axi_data_V_3_reg_372 = axi_data_V_1_reg_312.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read())))) {
        axi_data_V_3_reg_372 = AXI_video_strm_V_data_V_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        axi_last_V1_reg_259 = tmp_last_V_reg_491.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        axi_last_V1_reg_259 = axi_last_V_3_reg_360.read();
    }
    if (esl_seteq<1,1,1>(ap_condition_249.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(brmerge_fu_438_p2.read(), ap_const_lv1_1))) {
            axi_last_V_2_reg_335 = ap_phi_mux_eol_1_phi_fu_304_p4.read();
        } else if ((esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read()))) {
            axi_last_V_2_reg_335 = AXI_video_strm_V_last_V_dout.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            axi_last_V_2_reg_335 = ap_phi_reg_pp1_iter1_axi_last_V_2_reg_335.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        axi_last_V_3_reg_360 = eol_1_reg_301.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read())))) {
        axi_last_V_3_reg_360 = AXI_video_strm_V_last_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        eol_1_reg_301 = axi_last_V_2_reg_335.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_413_p2.read()))) {
        eol_1_reg_301 = axi_last_V1_reg_259.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        eol_2_reg_384 = eol_reg_323.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read())))) {
        eol_2_reg_384 = AXI_video_strm_V_last_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        eol_reg_323 = axi_last_V_2_reg_335.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_413_p2.read()))) {
        eol_reg_323 = ap_const_lv1_0;
    }
    if (esl_seteq<1,1,1>(ap_condition_249.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(brmerge_fu_438_p2.read(), ap_const_lv1_1))) {
            p_Val2_s_reg_348 = ap_phi_mux_axi_data_V_1_phi_fu_315_p4.read();
        } else if ((esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read()))) {
            p_Val2_s_reg_348 = AXI_video_strm_V_data_V_dout.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            p_Val2_s_reg_348 = ap_phi_reg_pp1_iter1_p_Val2_s_reg_348.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        sof_1_fu_204 = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sof_1_fu_204 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_424_p2.read()))) {
        t_V_2_reg_290 = j_V_fu_429_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_413_p2.read()))) {
        t_V_2_reg_290 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        t_V_reg_279 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        t_V_reg_279 = i_V_reg_507.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_reg_512 = exitcond_fu_424_p2.read();
        exitcond_reg_512_pp1_iter1_reg = exitcond_reg_512.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_V_reg_507 = i_V_fu_418_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_4_reg_530 = ap_phi_mux_p_Val2_s_phi_fu_352_p4.read().range(15, 8);
        tmp_5_reg_535 = ap_phi_mux_p_Val2_s_phi_fu_352_p4.read().range(23, 16);
        tmp_8_reg_525 = tmp_8_fu_444_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(AXI_video_strm_V_id_V0_status.read(), ap_const_logic_1))) {
        tmp_data_V_reg_483 = AXI_video_strm_V_data_V_dout.read();
        tmp_last_V_reg_491 = AXI_video_strm_V_last_V_dout.read();
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read())))) {
        AXI_video_strm_V_data_V_blk_n = AXI_video_strm_V_data_V_empty_n.read();
    } else {
        AXI_video_strm_V_data_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_read() {
    AXI_video_strm_V_data_V_read = AXI_video_strm_V_id_V0_update.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_dest_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read())))) {
        AXI_video_strm_V_dest_V_blk_n = AXI_video_strm_V_dest_V_empty_n.read();
    } else {
        AXI_video_strm_V_dest_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_dest_V_read() {
    AXI_video_strm_V_dest_V_read = AXI_video_strm_V_id_V0_update.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_id_V0_status() {
    AXI_video_strm_V_id_V0_status = (AXI_video_strm_V_data_V_empty_n.read() & AXI_video_strm_V_keep_V_empty_n.read() & AXI_video_strm_V_strb_V_empty_n.read() & AXI_video_strm_V_user_V_empty_n.read() & AXI_video_strm_V_last_V_empty_n.read() & AXI_video_strm_V_id_V_empty_n.read() & AXI_video_strm_V_dest_V_empty_n.read());
}

void AXIvideo2Mat::thread_AXI_video_strm_V_id_V0_update() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(AXI_video_strm_V_id_V0_status.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op59_read_state6.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        AXI_video_strm_V_id_V0_update = ap_const_logic_1;
    } else {
        AXI_video_strm_V_id_V0_update = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_id_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read())))) {
        AXI_video_strm_V_id_V_blk_n = AXI_video_strm_V_id_V_empty_n.read();
    } else {
        AXI_video_strm_V_id_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_id_V_read() {
    AXI_video_strm_V_id_V_read = AXI_video_strm_V_id_V0_update.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_keep_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read())))) {
        AXI_video_strm_V_keep_V_blk_n = AXI_video_strm_V_keep_V_empty_n.read();
    } else {
        AXI_video_strm_V_keep_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_keep_V_read() {
    AXI_video_strm_V_keep_V_read = AXI_video_strm_V_id_V0_update.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read())))) {
        AXI_video_strm_V_last_V_blk_n = AXI_video_strm_V_last_V_empty_n.read();
    } else {
        AXI_video_strm_V_last_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_read() {
    AXI_video_strm_V_last_V_read = AXI_video_strm_V_id_V0_update.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_strb_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read())))) {
        AXI_video_strm_V_strb_V_blk_n = AXI_video_strm_V_strb_V_empty_n.read();
    } else {
        AXI_video_strm_V_strb_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_strb_V_read() {
    AXI_video_strm_V_strb_V_read = AXI_video_strm_V_id_V0_update.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read())))) {
        AXI_video_strm_V_user_V_blk_n = AXI_video_strm_V_user_V_empty_n.read();
    } else {
        AXI_video_strm_V_user_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_read() {
    AXI_video_strm_V_user_V_read = AXI_video_strm_V_id_V0_update.read();
}

void AXIvideo2Mat::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[4];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[7];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[5];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[6];
}

void AXIvideo2Mat::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AXIvideo2Mat::thread_ap_block_pp1_stage0_01001() {
    ap_block_pp1_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op59_read_state6.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_0_V_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_1_V_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_2_V_full_n.read())))));
}

void AXIvideo2Mat::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op59_read_state6.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_0_V_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_1_V_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_2_V_full_n.read())))));
}

void AXIvideo2Mat::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op59_read_state6.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_0_V_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_1_V_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_2_V_full_n.read())))));
}

void AXIvideo2Mat::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void AXIvideo2Mat::thread_ap_block_state5_pp1_stage0_iter0() {
    ap_block_state5_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AXIvideo2Mat::thread_ap_block_state6_pp1_stage0_iter1() {
    ap_block_state6_pp1_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op59_read_state6.read()));
}

void AXIvideo2Mat::thread_ap_block_state7_pp1_stage0_iter2() {
    ap_block_state7_pp1_stage0_iter2 = ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_0_V_full_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_1_V_full_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_2_V_full_n.read())));
}

void AXIvideo2Mat::thread_ap_block_state9() {
    ap_block_state9 = (esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read()));
}

void AXIvideo2Mat::thread_ap_condition_249() {
    ap_condition_249 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0));
}

void AXIvideo2Mat::thread_ap_condition_287() {
    ap_condition_287 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0));
}

void AXIvideo2Mat::thread_ap_condition_pp1_exit_iter1_state6() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_0))) {
        ap_condition_pp1_exit_iter1_state6 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter1_state6 = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_413_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void AXIvideo2Mat::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void AXIvideo2Mat::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter2.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_ap_phi_mux_axi_data_V_1_phi_fu_315_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()))) {
        ap_phi_mux_axi_data_V_1_phi_fu_315_p4 = p_Val2_s_reg_348.read();
    } else {
        ap_phi_mux_axi_data_V_1_phi_fu_315_p4 = axi_data_V_1_reg_312.read();
    }
}

void AXIvideo2Mat::thread_ap_phi_mux_eol_1_phi_fu_304_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()))) {
        ap_phi_mux_eol_1_phi_fu_304_p4 = axi_last_V_2_reg_335.read();
    } else {
        ap_phi_mux_eol_1_phi_fu_304_p4 = eol_1_reg_301.read();
    }
}

void AXIvideo2Mat::thread_ap_phi_mux_eol_2_phi_fu_387_p4() {
    ap_phi_mux_eol_2_phi_fu_387_p4 = eol_2_reg_384.read();
}

void AXIvideo2Mat::thread_ap_phi_mux_eol_phi_fu_327_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()))) {
        ap_phi_mux_eol_phi_fu_327_p4 = axi_last_V_2_reg_335.read();
    } else {
        ap_phi_mux_eol_phi_fu_327_p4 = eol_reg_323.read();
    }
}

void AXIvideo2Mat::thread_ap_phi_mux_p_Val2_s_phi_fu_352_p4() {
    if (esl_seteq<1,1,1>(ap_condition_287.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(brmerge_fu_438_p2.read(), ap_const_lv1_1)) {
            ap_phi_mux_p_Val2_s_phi_fu_352_p4 = ap_phi_mux_axi_data_V_1_phi_fu_315_p4.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read())) {
            ap_phi_mux_p_Val2_s_phi_fu_352_p4 = AXI_video_strm_V_data_V_dout.read();
        } else {
            ap_phi_mux_p_Val2_s_phi_fu_352_p4 = ap_phi_reg_pp1_iter1_p_Val2_s_reg_348.read();
        }
    } else {
        ap_phi_mux_p_Val2_s_phi_fu_352_p4 = ap_phi_reg_pp1_iter1_p_Val2_s_reg_348.read();
    }
}

void AXIvideo2Mat::thread_ap_phi_reg_pp1_iter1_axi_last_V_2_reg_335() {
    ap_phi_reg_pp1_iter1_axi_last_V_2_reg_335 =  (sc_lv<1>) ("X");
}

void AXIvideo2Mat::thread_ap_phi_reg_pp1_iter1_p_Val2_s_reg_348() {
    ap_phi_reg_pp1_iter1_p_Val2_s_reg_348 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
}

void AXIvideo2Mat::thread_ap_predicate_op59_read_state6() {
    ap_predicate_op59_read_state6 = (esl_seteq<1,1,1>(exitcond_reg_512.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_438_p2.read()));
}

void AXIvideo2Mat::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_413_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_brmerge_fu_438_p2() {
    brmerge_fu_438_p2 = (sof_1_fu_204.read() | ap_phi_mux_eol_phi_fu_327_p4.read());
}

void AXIvideo2Mat::thread_exitcond2_fu_413_p2() {
    exitcond2_fu_413_p2 = (!t_V_reg_279.read().is_01() || !img_rows_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_279.read() == img_rows_V_read.read());
}

void AXIvideo2Mat::thread_exitcond_fu_424_p2() {
    exitcond_fu_424_p2 = (!t_V_2_reg_290.read().is_01() || !img_cols_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_2_reg_290.read() == img_cols_V_read.read());
}

void AXIvideo2Mat::thread_i_V_fu_418_p2() {
    i_V_fu_418_p2 = (!t_V_reg_279.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_reg_279.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void AXIvideo2Mat::thread_img_data_stream_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()))) {
        img_data_stream_0_V_blk_n = img_data_stream_0_V_full_n.read();
    } else {
        img_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_img_data_stream_0_V_din() {
    img_data_stream_0_V_din = tmp_8_reg_525.read();
}

void AXIvideo2Mat::thread_img_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        img_data_stream_0_V_write = ap_const_logic_1;
    } else {
        img_data_stream_0_V_write = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_img_data_stream_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()))) {
        img_data_stream_1_V_blk_n = img_data_stream_1_V_full_n.read();
    } else {
        img_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_img_data_stream_1_V_din() {
    img_data_stream_1_V_din = tmp_4_reg_530.read();
}

void AXIvideo2Mat::thread_img_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        img_data_stream_1_V_write = ap_const_logic_1;
    } else {
        img_data_stream_1_V_write = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_img_data_stream_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()))) {
        img_data_stream_2_V_blk_n = img_data_stream_2_V_full_n.read();
    } else {
        img_data_stream_2_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_img_data_stream_2_V_din() {
    img_data_stream_2_V_din = tmp_5_reg_535.read();
}

void AXIvideo2Mat::thread_img_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_512_pp1_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        img_data_stream_2_V_write = ap_const_logic_1;
    } else {
        img_data_stream_2_V_write = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_j_V_fu_429_p2() {
    j_V_fu_429_p2 = (!t_V_2_reg_290.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_2_reg_290.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void AXIvideo2Mat::thread_tmp_8_fu_444_p1() {
    tmp_8_fu_444_p1 = ap_phi_mux_p_Val2_s_phi_fu_352_p4.read().range(8-1, 0);
}

void AXIvideo2Mat::thread_tmp_user_V_fu_404_p1() {
    tmp_user_V_fu_404_p1 = AXI_video_strm_V_user_V_dout.read();
}

void AXIvideo2Mat::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(AXI_video_strm_V_id_V0_status.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_404_p1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(AXI_video_strm_V_id_V0_status.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_user_V_fu_404_p1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond2_fu_413_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 16 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read())))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_384.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_id_V0_status.read())) && esl_seteq<1,1,1>(ap_phi_mux_eol_2_phi_fu_387_p4.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

